### ISSUE TITLE
qmake - error

### ISSUE THREAD

**Issue by thewurx** [monero-project/monero-core#10]
Hi Guys,

Firstly. Thanks for the great work. 

Error I get is with qmake:

**qmake: could not exec '/usr/lib/x86_64-linux-gnu/qt4/bin/qmake': No such file or directory**

Followed instructions for the Linux Mint 18 64bit package. Running on Asus X554L machine. Core i3 4GB Ram. (Same issue on my tower Core i3 8GB Ram Linux Mint 18)

edit: the folder /usr/lib/x86_64-linux-gnu/qt4/bin/ exists. No qmake file in the directory. Only a qdbus file in the said directory.

Tired: sudo apt-get install qt4-qmake libqt4-dev

New error:

**qmake
/home/######/monero-core/monero-core.pro:146: Unknown replace function: shell_path
Project MESSAGE: Warning: unknown QT: qml**

Also tried:apt-get update && upgrade     no luck

**Comment by mbg033** [comment]
Hi, seems you installed qt4 but it needs to be qt5.  If you followed README already, you probably need to setup default Qt version. On Ubuntu (same for Mint I guess)  it can be done with qtchooser package

**Comment by medusadigital** [comment]
can be closed
