### ISSUE TITLE
The UI seems to break on split transactions

### ISSUE THREAD

**Issue by moneromooo-monero** [monero-project/monero-core#113]
src/wallet/api/pending_transaction.cpp:    assert(m_pending_tx.size() == 1);

**Comment by medusadigital** [comment]
@mbg033 can you fix this one? pretty imporant

**Comment by mbg033** [comment]
yep, will try

**Comment by mbg033** [comment]
@moneromooo-monero, can you help with tx splitting? is there a way for force it? I'm always getting 1 tx

**Comment by moneromooo-monero** [comment]
Try sending close to your whole balance with highest mixin.

Otherwise, if that still makes only one, find create_transactions_2 in src/wallet/wallet2.cpp, look for "if (try_tx)" in that function, and set try_tx to true just before.

**Comment by mbg033** [comment]
ok, it seems I just forgot to remove that assert, it works. Added `PendingTransaction::txCount()` method to API: https://github.com/monero-project/monero-core/pull/129

**Comment by fluffypony** [comment]
Closing as fixed
