### ISSUE TITLE
Allow to select public nodes as daemon address in the wizard

### ISSUE THREAD

**Issue by maitscha** [monero-project/monero-core#121]
Currently the GUI has localhost:18081 as default daemon address. I think the GUI should allow to select public nodes as daemon address. There was already a proposal on Reddit some days ago:

https://www.reddit.com/r/Monero/comments/5aq5y3/open_node_network_expansion_for_gui_release/

With an option to use one of the public nodes the GUI can be used instantly, and the users don't have to wait until the blockchain has been synced. I think this would be for non-experienced users, and for users who want to try out Monero (and the wallet GUI) a great benefit.

The GUI-integrated daemon as proposed in #39 would be still required for users who want not use a public node because of privacy issues.

What do you think about it?

**Comment by moneromooo-monero** [comment]
It is editable. AFAICT, thisalready works. If you're claiming it does not, say so specifically, and include any errors you get.
Note that using a remote daemon isn't a good idea due to changing RPC anyway. YMMV.

**Comment by maitscha** [comment]
The daemon address is already editable in the UI, but the inexperienced user may not know how to use a public node. The idea was to provide an "editable" select input field, where the user can select one of the known public nodes, or enter its own custom address.

**Comment by dEBRUYNE-1** [comment]
As far as I know this will be part of @Jaqueeee's daemon integration.

**Comment by medusadigital** [comment]
can this be closed ? or is there something that needs to be done ?
