### ISSUE TITLE
Transaction history can dissapear depending on advanced filter

### ISSUE THREAD

**Issue by medusadigital** [monero-project/monero-core#123]
Transaction history can dissapear depending on advanced filter.

Reproduce:

- open monero-core freshly
- go to transaction history tab
- swictch advanced filter to "SENT"
- press filter button
- switch advanced gilter to "ALL"
- press filter button

**Comment by mbg033** [comment]
@medusadigital, I just checked it with my [develop](https://github.com/mbg033/monero-core/commits/develop), couldn't reproduce the issue. This branch contains merged PRs: https://github.com/monero-project/monero-core/pull/119, https://github.com/monero-project/monero-core/pull/120

**Comment by medusadigital** [comment]
ok, will try again once stuff merged. too many PRs pending right now to get a clear picture. 
when i tried i tested without #119 and #120.

**Comment by M5M400** [comment]
tried to reproduce this, but advanced filter does not work at all for me. I can set to "sent", "received", enter min/max amounts... it always shows me the complete history, no matter how often I hit the "filter" button. c9bb2f5

**Comment by taushet** [comment]
I could not reproduce this.

**Comment by medusadigital** [comment]
cant reproduce myself either, seems to be an anomaly --> close
