### ISSUE TITLE
The GUI should check RPC version and complain if the daemon is too old

### ISSUE THREAD

**Issue by moneromooo-monero** [monero-project/monero-core#124]
Using an old daemon will mean the GUI can't send, as the histogram RPC was modified to add returns which an old daemon won't return, causing the wallet to not find what it's looking for.

**Comment by moneromooo-monero** [comment]
https://github.com/monero-project/monero-core/pull/128

**Comment by dternyak** [comment]
#128 is merged, this can be closed right @moneromooo-monero ?

**Comment by fluffypony** [comment]
Closing as fixed
