### ISSUE TITLE
Transfer: implement "busy indicator" while creating and committing transaction

### ISSUE THREAD

**Issue by mbg033** [monero-project/monero-core#130]
probably by implementing async versions of `Wallet::createTransaction()` and `PendingTransaction::commit()`

**Comment by Jaqueeee** [comment]
@mbg033 I'm working on this one. I'm also replacing the standard dialogs with custom.

**Comment by M5M400** [comment]
great - saves me to suggest custom dialogs for TX stuff :+1:
