### ISSUE TITLE
Title bar should be permanently shown

### ISSUE THREAD

**Issue by antanst** [monero-project/monero-core#141]
The fact that the title bar is in "auto-hide" mode, has the following consequences:

* The title bar has to be activated for the window to be moved. Because it can't be activated when a dialog is shown (like the password or sync progress dialogs) there's no way to move the window then.

* It's a non-standard behaviour that confuses new users.

I suggest that the title bar is fixed and on by default as in almost all applications.

**Comment by moneromooo-monero** [comment]
I'm unsure what it is for. I think it might as well be removed, as it doesn't actually do anything AFAICT.
Moving the window works just fine using the window manager's top bar here.

**Comment by antanst** [comment]
I'm not sure I understood your comment. At least in Linux, the window manager's topbar is overridden by the GUI's custom top bar (which is black and has the close buttons on the right, contrary to system defaults). In addition, this top bar is hidden automatically by default, hence my initial comment.

**Comment by Jaqueeee** [comment]
@mbg033 Can we make top bar permanently visible or is there a reason it behaves this way?

**Comment by dternyak** [comment]
I agree with this being an issue on macOS and also agree with the solution being to make the top bar permanently visible.

**Comment by medusadigital** [comment]
the only downside would be that the cool rainbow stripe on top wouldnt be visible anymore (is this a leftover of the initial color choices ?) . anyway im cool with everything personally.

**Comment by mbg033** [comment]
@Jaqueeee, yes, we obviously can, but it was designed "auto-hidden" from the beginning (not by me). Anyway, I can prepare PR with permanently visible titlebar soon.

**Comment by M5M400** [comment]
I second that request. In simple view the title bar is also fixed. I prefer that.

**Comment by antanst** [comment]
Thanks for the fix! Closing.
