### ISSUE TITLE
Can't open existing wallet created in monero cli v0.10.0

### ISSUE THREAD

**Issue by tikwanleap** [monero-project/monero-core#149]
![image](https://cloud.githubusercontent.com/assets/4574465/20193413/b767b4b4-a742-11e6-9b3e-607565ed7360.png)

Error message:
`Couldn't open wallet: basic_string::M_replace_aux`

I used hyc's windows gui build from here:

http://highlandsun.com/hyc/monero-core.win.x86.v0-1-0-0.zip
sha1sum 69daa76ca59a375cb127b6fac62b224e7ad44e02

**Comment by Jaqueeee** [comment]
Was the wallet created with 32bit or 64bit cli wallet?

**Comment by tikwanleap** [comment]
64 bit cli wallet. Downloaded from here:
https://downloads.getmonero.org/monero.win.x64.v0-10-0-0.zip

**Comment by Jaqueeee** [comment]
ok. thanks. Could you try to remove (move to different location) the cache file (the one without .keys or address.txt suffix) and try to open it again?

**Comment by tikwanleap** [comment]
That seems to fix it. It is syncing now.

**Comment by Jaqueeee** [comment]
Good to hear. Unfortunately the cache file isn't compatible between 64/32bit.

**Comment by tikwanleap** [comment]
Got it. Thanks for the help!

**Comment by dEBRUYNE-1** [comment]
We should, preferably, leave this open for visibility.

**Comment by dternyak** [comment]
Any way to catch that error?

After the catch, you could potentially delete the cache file in the code itself, then retry. Seems like the best experience for the user, and not any downside(?).

**Comment by moneromooo-monero** [comment]
Losing your history, especiually the tx keys, seems like a pretty large donwside.

**Comment by dternyak** [comment]
@moneromooo-monero Good point - maybe offer that option to the user then via prompt? Most users will just say yes and wait for it to rebuild (imo).

**Comment by maitscha** [comment]
@moneromooo-monero so someone really loses information if the cache is rebuild? I think a prompt with a question "Do you really want to rebuild the cache?" would be a good alternative.

**Comment by dternyak** [comment]
@maitscha We must have commented at the exact same time - seems like its a decent idea if we both came up with it independently.

**Comment by fluffypony** [comment]
Closed as fixed - further discussion can be pushed to its own issue

**Comment by medusadigital** [comment]
@dternyak @maitscha  we decided to close this issue since it basically boils down to the question: should we warn users  if they are opening an x86 cache with an x64 wallet, since the cache will get rebuilt and overwritten? perosnally i have trust in the user and belive we can not protect him from every mistake he does, but we can disuss that as fluffy said in a new issue.

**Comment by Jaqueeee** [comment]
@medusadigital @dternyak @maitscha 
To clarify, nothing gets deleted/overwritten automatically. To rebuild cache the user first has to delete or move the cache file.

**Comment by dternyak** [comment]
@Jaqueeee @fluffypony Don't you think we should still try to suppress this exception and show an alert in the UI at the least? Closing this issue means its ok to just let the GUI crash, and the user should be able to figure out that they need to delete the cache file.

**Comment by maitscha** [comment]
I also think that the user should get at least a hint how it can be fixed (by deleting the cache file).

**Comment by Jaqueeee** [comment]
@dternyak @maitscha 
Yes. I agree. I'll add a better error msg. hopefully this won't be a big issue when we have 64 bit binaries.
