### ISSUE TITLE
"Language: Italy"

### ISSUE THREAD

**Issue by taushet** [monero-project/monero-core#150]
We are mixing adjectives and nouns! The horror!

We need to agree on either:

`Language: Italian`

or 

`Region: Italy`

I support the former (which is in keeping with conventions) and thus the list 'English (US)' vs 'English (UK)' vs 'Arabic (Palestine)' vs 'Norwegian (Bokmal)' vs 'Norwegian (Nynorsk)', etc., etc.

**Comment by taushet** [comment]
I can fix this, but will wait on the current PRs to be committed.

**Comment by dEBRUYNE-1** [comment]
See comments on #132.

**Comment by taushet** [comment]
Agreed. So native language names then!

**Comment by maitscha** [comment]
Do we also need updates for the German translations?

**Comment by dEBRUYNE-1** [comment]
@maitscha Afaik, yes.

**Comment by maitscha** [comment]
@dEBRUYNE-1 Is there a tool to update the existing translation file, or should I update it manually?

**Comment by dEBRUYNE-1** [comment]
You can regenerate the English file automatically as far as I know. From that you can easily translate the new strings manually. @Jaqueeee is probably able to explain how to do this.

**Comment by maitscha** [comment]
`lupdate monero-core.pro` did the trick ;)

**Comment by fluffypony** [comment]
Closing as fixed
