### ISSUE TITLE
After closing wallet 1 and opening wallet 2, GUI incorrectly displays receive address for wallet 1.

### ISSUE THREAD

**Issue by tikwanleap** [monero-project/monero-core#154]
Steps to reproduce:
1. Open wallet 1.
2. Note receive address.
3. Close wallet 1.
4. Open wallet 2.
5. The receive address is the same as wallet 1. Should have updated to match wallet 2.

Temporary workaround:
1. Click the "Generate" button next to Payment ID. This will update to the correct receive address.

**Comment by dEBRUYNE-1** [comment]
Can confirm. I was able to reproduce this.

**Comment by taushet** [comment]
Yep, me too.

**Comment by moneromooo-monero** [comment]
https://github.com/monero-project/monero-core/pull/155

**Comment by taushet** [comment]
Good pickup, btw. This could have had nasty consequenses if undiscovered.

**Comment by tikwanleap** [comment]
Thanks! Happy to help and really glad this was fixed quickly. Great job moneromooo-monero!

**Comment by dEBRUYNE-1** [comment]
Can confirm the fix works.

**Comment by dternyak** [comment]
@tikwanleap This can be closed right @taushet ?

**Comment by fluffypony** [comment]
Closing as fixed
