### ISSUE TITLE
Rename "Transfer" tab to "Send"

### ISSUE THREAD

**Issue by woodser** [monero-project/monero-core#159]
Send and receive are standard concepts people are familiar with, whereas transfer is ambiguous because it could mean send or receive, both of which are technically transfers.

I propose we rename the "Transfer" tab to "Send" for clarity.

**Comment by M5M400** [comment]
I second that request

**Comment by maitscha** [comment]
Perhaps also change "Sign/verify" to "Sign & Verify"?

**Comment by xmr-eric** [comment]
I think the current "Sign/verify" is better, because the slash has connotations of and/or. You can sign and verify here. You can also sign _or_ verify.

**Comment by xmr-eric** [comment]
Issue can be closed

**Comment by xmr-eric** [comment]
@woodser Issue can be closed

**Comment by woodser** [comment]
@xmr-eric thank you!
