### ISSUE TITLE
Translations not working - selected language not used

### ISSUE THREAD

**Issue by maitscha** [monero-project/monero-core#164]
I have tried to activate german and italian translations in `lang/languages.xml`. The languages are available in the welcome screen, and once selected activated for the first wizard page. But the application itself does not use the selected language. The language selection is also not persisted in the property store of Qt (tested on MacOS):

```
# defaults read org.getmonero.monero-core
{
    "account_name" = foo;
    "allow_background_mining" = 0;
    "auto_donations_amount" = 0;
    "auto_donations_enabled" = 0;
    "daemon_address" = "localhost:18081";
    "is_recovering" = 0;
    language = "US English";
    locale = "en_US";
    ...
}

```

There has already some work done for translations (TranslationManager.cpp, WizardWelcome.qml), but I have basically no idea how the translation stuff should work.

Perhaps someone can have a look at it, so that we can add some more languages.

**Comment by Jaqueeee** [comment]
@mbg033 can you confirm if translations are working or if they aren't fully implemented yet?

**Comment by mbg033** [comment]
@Jaqueeee yes translations are working but there should be actual translated strings. Also, I can confirm "language" and "locale" settings persists. At least on Ubuntu. 
This issue could be with Debug build - long time ago I disabled translations update/generation for debug build as forced re-link everytime, which took about 30 seconds. Recently I figure out if we link debug monero-core with debug libwallet_api - it processed quite fast, so I will enable "translations update for debug build" in next PR

**Comment by maitscha** [comment]
With the latest changes, I get the following build error (MacOS). I'm trying to rebuild monero with `./get_libwallet_api.sh Debug`:

```
Install the project...
-- Install configuration: "Debug"
-- Installing: /Users/foo/monero-core/monero/lib/libunbound.a
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: /Users/foo/monero-core/monero/lib/libunbound.a(checklocks.c.o) has no symbols
```

What could be the reason?

**Comment by maitscha** [comment]
**Update**: After I changed the MacOS `defaults` with the following command, the language is used for the UI: ``defaults write org.getmonero.monero-core locale de``. So it seams the selected language is not persisted under MacOS.

**Comment by dEBRUYNE-1** [comment]
+resolved
