### ISSUE TITLE
Transfer tab background color

### ISSUE THREAD

**Issue by peronero** [monero-project/monero-core#165]
The grey background color of the Transfer tab/page is visibly darker than the grey background in any other tab - the lighter version seems to be correct and is more pleasant to the eye.

Using Tumbleweed with GNOME.

**Comment by M5M400** [comment]
Can't verify that on current master and never noticed that before. Can you make screenshots and post the commit you're on? Might speed up things.

**Comment by moneromooo-monero** [comment]
This happens when you can't transfer (eg, daemon disconnected, etc)

**Comment by taushet** [comment]
@moneromooo-monero is that clear enough to the user though?

**Comment by peronero** [comment]
This isn't very clear to the user as @taushet points out - a shade of red would be more indicative of something 'not being right', but a different shade of grey just takes away from a consistent user experience.

A user in this case - where he is blocked from doing something by a dependency on another functionality - is ideally expecting text fields and buttons to be inaccessible and their inaccessibility to be visually communicated, along with an explanation of what is wrong and perhaps even a visual indicator where he can fix this and/or monitor progress (blinking sync status perhaps).

**Comment by Jaqueeee** [comment]
This change is implemented in the Daemon integration branch i'm working on.
https://github.com/monero-project/monero-core/commit/a78b8f5e3a54a71fa06a1490af541bce5aec861c

**Comment by peronero** [comment]
Doesn't look fixed on a fresh build from master - background color on only this tab is still darker than on any other tabs.
