### ISSUE TITLE
Navigation menu horizontal artifacts

### ISSUE THREAD

**Issue by peronero** [monero-project/monero-core#166]
I'm seeing horizontal lines that appear below only the Transfer  after Verify Payment tabs after being on those those tabs and then moving onto another tab. They do not disappear afterwards.

Steps to reproduce:

1. Open monero-core (Transfer is selected by default)
2. Select another tab  - the horizontal line below Transfer will now appear

Also occurs after selecting the Verify Payments tab and moving to another tab - see screenshot.

![screenshot from 2016-11-14 19-45-08](https://cloud.githubusercontent.com/assets/22800288/20288669/eeb52c2c-aaa2-11e6-9bf6-527149813486.png)

Tumbleweed with GNOME.

**Comment by xmr-eric** [comment]
I've noticed this too

**Comment by iDunk5400** [comment]
I suppose it is these two separators that bother you.

https://github.com/monero-project/monero-core/blob/master/LeftPanel.qml#L241-L247
https://github.com/monero-project/monero-core/blob/master/LeftPanel.qml#L279-L285

**Comment by xmr-eric** [comment]
@iDunk5400 I don't think it's the separators themselves that are the problem. Moreso that they come and go sporadically, or at least, that's my experience.

**Comment by Jaqueeee** [comment]
Fixed in https://github.com/monero-project/monero-core/issues/195

**Comment by peronero** [comment]
Confirmed fixed.
