### ISSUE TITLE
Settings' Seed text field uses GTK styling

### ISSUE THREAD

**Issue by peronero** [monero-project/monero-core#167]
The seed text field in the Settings tab appears to use styling from the GTK theme unlike any other field - problematic/unattractive if using a non-standard/dark theme.

![screenshot from 2016-11-15 10-20-13](https://cloud.githubusercontent.com/assets/22800288/20311336/6387a082-ab1d-11e6-9100-73ef2351de73.png)

Tumbleweed with GNOME.

**Comment by xmr-eric** [comment]
Copy to clipboard looks covered?
