### ISSUE TITLE
amount and Fee can overlap when using big amounts

### ISSUE THREAD

**Issue by medusadigital** [monero-project/monero-core#179]
![bigamount](https://cloud.githubusercontent.com/assets/17108301/20409320/7f47a206-ad19-11e6-9d70-d1fcc2647dfb.png)

screen resolution is 2560x1440, Ubuntu 16

**Comment by moneromooo-monero** [comment]
Someone else reporting that there's an almost overlap, screen width 1920.

Looks OK here, with 1280. So it looks like the wider the screen, the less space there is, unexpectedly.
