### ISSUE TITLE
"wallet/wallet2_api.h: No such file or directory" when running make

### ISSUE THREAD

**Issue by hackmyl1fe** [monero-project/monero-core#18]
I tried to install monero-core multiple times now and i keep running into the same error.

I run ./get_libwallet_api.sh and it finishes successfully. I run qmake, I does not give me any outputs.
Then I run make and it complains about a missing file. The file is actually there but under bitmonero/src/wallet and not src/wallet. Im not sure if im missing some steps but im following the install guide.

Im running ubuntu 16.04 in a VM in case this is an issue

**Comment by radfish** [comment]
You need to manually merge PR #14 in order to build, because monero daemon repo was updated to not build/install wallet lib/headers by default (need to pass `BUILD_GUI_DEPS=ON` option).

**Comment by medusadigital** [comment]
solution got merged to master with https://github.com/monero-project/monero-core/commit/c87eed558fa564509c611625d75a2f8ae7357527

no more issues, can be closed
