### ISSUE TITLE
Integrated PaymentId missing

### ISSUE THREAD

**Issue by medusadigital** [monero-project/monero-core#181]
If i send money from A to B's integrated Address, the payment ID doesnt show up in wallet A and neither in wallet B.

this seems to be GUI related only, the same test worked fine with the CLI wallet.

1.)

![integrated_broken_confirm](https://cloud.githubusercontent.com/assets/17108301/20426418/4e4e49b4-ad7f-11e6-8ee0-04f0a44667f0.png)

2.)

![integrated_broken_confirm_2](https://cloud.githubusercontent.com/assets/17108301/20426427/55fd4cfa-ad7f-11e6-85a7-9fa014c475e3.png)

3.)

![integrated_broken_confirm_3](https://cloud.githubusercontent.com/assets/17108301/20426429/5d1f8f48-ad7f-11e6-9f52-d6073a75451c.png)

**Comment by dEBRUYNE-1** [comment]
Can confirm this.

**Comment by moneromooo-monero** [comment]
https://github.com/monero-project/monero/pull/1356

**Comment by medusadigital** [comment]
fixed -> closed
