### ISSUE TITLE
TRX Construction with amount (all) always uses default mixing

### ISSUE THREAD

**Issue by medusadigital** [monero-project/monero-core#182]
![amount_all](https://cloud.githubusercontent.com/assets/17108301/20427075/73d9124c-ad82-11e6-950b-04226f34220c.png)

**Comment by dEBRUYNE-1** [comment]
Confirmation window also doesn't properly show the mixin #. For me it shows mixin: 0.

**Comment by M5M400** [comment]
+1 reproduced

**Comment by owlcatz** [comment]
Thank you, medusadigital! :)

**Comment by moneromooo-monero** [comment]
https://github.com/monero-project/monero-core/pull/183

**Comment by medusadigital** [comment]
fixed -> closed
