### ISSUE TITLE
Crash on Mac 10.12.1

### ISSUE THREAD

**Issue by dternyak** [monero-project/monero-core#191]
[This](http://imgur.com/a/bmyV3) album created by a user on [reddit](https://www.reddit.com/r/Monero/comments/5dujei/monero_gui_build_3_macos_unofficial_build_of/da7ekz0/?context=3&st=ivpqord5&sh=d0bf3529) shows a crash on Mac. 

It seems like there is a dependency on QT - it should be included in the binary so that users don't need to have it installed externally. 

Another report:
   - Termination Reason: DYLD, [0x1] Library missing 
   - Application Specific Information: dyld: launch, loading dependent libraries
Dyld Error Message: Library not loaded: @rpath/QtQuick.framework/Versions/5/QtQuick Referenced from: /private/var/folders/*/monero-core.app/Contents/MacOS/monero-core Reason: image not found

**Comment by dEBRUYNE-1** [comment]
Are we certain the binary distributed by Vertp was built correctly by him?

**Comment by dternyak** [comment]
Well there's not much that can go wrong when building it, and I can confirm it works on macOs with QT installed on it. Just a simple `bash build.sh` after `./get_libwallet_api.sh`

**Comment by Jaqueeee** [comment]
There are some extra steps involved when deploying for platforms that don't have the dependencies installed (i.e. boost, openssl). The boost brew package also needs to be custom built to support older hardware. Same issue we had on older windows machines. I'll update the docs when i've sorted this out.

**Comment by Jaqueeee** [comment]
@dternyak 
Could you try this build?
https://www.dropbox.com/s/it6woiru9nf5s2v/monero-core-osx-jaquee.zip?dl=0
sha1 ad7cb969e7a7dcf47610ef8a92eee90bdb836e2e

**Comment by sfinkz** [comment]
@Jaqueeee It works beautifully for me. Only issue I've seen is the window flickering when resizing with the mouse by dragging the icon at the right bottom corner.

**Comment by dternyak** [comment]
@sfinkz Can you confirm you do not have QT installed on your machine?

**Comment by sfinkz** [comment]
@dternyak I am sorry, Indeed I have. Will remove the message.

**Comment by dternyak** [comment]
@sfinkz No need to remove your message, the bug simply appears only when a user does not have QT installed on their system, so that is what we are trying to test.

**Comment by medusadigital** [comment]
ok so the open question of mac deployment seems to be solved ?

**Comment by dternyak** [comment]
@medusadigital I'd like to see a PR with updated build instructions before I mark this issue as closed, do you agree @Jaqueeee ?

**Comment by Jaqueeee** [comment]
Agreed @dternyak

**Comment by Jaqueeee** [comment]
Sorry, I never updated those instructions. But not sure if it's a good idea to clutter the Readme with deploy instructions anyway.
