### ISSUE TITLE
[Feature Request] - ability to select text in history tab

### ISSUE THREAD

**Issue by Gingeropolous** [monero-project/monero-core#198]
built commit c83336cc4714215725cba957d8ea164a57c33987

Is it possible to select any of the text on the history tab, so that I can copy and paste the text that is found there? 

Seems silly that it displays it but I can't select it and (for example) paste it into a block explorer.

**Comment by Gingeropolous** [comment]
This was built and run on Ubuntu 16.

**Comment by Jaqueeee** [comment]
All fields except amount and fee should be selectable by mouse AFAICT. Haven't tested on Ubuntu though. Can you confirm that block height isn't selectable for example?
https://github.com/monero-project/monero-core/blob/c83336cc4714215725cba957d8ea164a57c33987/components/HistoryTable.qml#L234

**Comment by Gingeropolous** [comment]
im an idiot. it works as it should.
