### ISSUE TITLE
MacOSX Build still points to testnet

### ISSUE THREAD

**Issue by xmrdc** [monero-project/monero-core#20]
Was able to successfully compile today on OSX El Capitan. The app currently points to testnet (in the org.getmonero.plist) and needs to point to mainnet.

**Comment by medusadigital** [comment]
can be closed once https://github.com/monero-project/monero-core/pull/32/commits/e287ce88bc6bed5f3d70ce3ee7e3f7287228798c is merged. The user can then select himself if he want to connect to testnet or not via checkbox

**Comment by xmrdc** [comment]
successfully built the latest, and connects to mainnet. closed.

**Comment by sammy007** [comment]
`Genesis block missmatch. You probably use wallet without testnet flag`. Just installed. Trying to use remote node.
