### ISSUE TITLE
QR-code on Receive page doesn't seem to work

### ISSUE THREAD

**Issue by peanutsformonkeys** [monero-project/monero-core#201]
Trying the [pre-beta](https://github.com/Jaqueeee/monero-core/releases/tag/pre-beta) build. Created a new wallet. The QR-code shown on the "Receive" page doesn't scan with the QR-code [app](http://itunes.apple.com/us/app/scan/id411206394) from [scan.me](https://scan.me) on my smartphone. E.g.:

![gui-qr](https://cloud.githubusercontent.com/assets/21346321/20610244/1e476a62-b297-11e6-96b8-2d205117d19a.png)

For reference, the QR-codes that are generated on [MoneroAddress.org](https://moneroaddress.org), do scan immediately with the same app. Another reddit user encountered the [same issue](https://www.reddit.com/r/Monero/comments/5emgio/unofficial_gui_builds/dae9qzk/). Needs to be looked at.

**Comment by SamsungGalaxyPlayer** [comment]
I can confirm the same issue. I'm using Barcode scanner (https://play.google.com/store/apps/details?id=com.google.zxing.client.android). This scanner works perfectly with MyMonero.

**Comment by moneromooo-monero** [comment]
https://github.com/monero-project/monero-core/pull/203

**Comment by Jaqueeee** [comment]
@SamsungGalaxyPlayer @peanutsformonkeys can you confirm if #203 (merged to master) fixes this issue?

**Comment by peanutsformonkeys** [comment]
@Jaqueeee I am now able to scan the generated QR-code with the [scan.be](https://scan.me/) on my smartphone:

<img width="250" alt="qr-20161220" src="https://cloud.githubusercontent.com/assets/21346321/21357037/1276a1a2-c6d4-11e6-96e9-7e2194bd6f0d.png">

**Comment by peanutsformonkeys** [comment]
Checked again with the [macOS beta](https://downloads.getmonero.org/gui/monero.gui.mac.x64.beta.tar.bz2).
