### ISSUE TITLE
Suggestion: Follow similar naming convention as the CLI

### ISSUE THREAD

**Issue by peanutsformonkeys** [monero-project/monero-core#202]
Currently, the Windows binary is named `monero-core.exe` and the macOS binary `monero-core.app`. Wouldn't it make sense to align the naming of these with that of the CLI? Such as `monero-wallet-gui.exe` and `monero-wallet-gui.app`?

**Comment by xmr-eric** [comment]
I think this is a great idea. In fact, the entire repository could be renamed to be monero-wallet-gui.

**Comment by peanutsformonkeys** [comment]
Looks like this is implemented now.
