### ISSUE TITLE
 Suggestion: GUI Wallet should have an option to use a remote node until it is fully sunchronised

### ISSUE THREAD

**Issue by sornros** [monero-project/monero-core#207]
The GUI should have an option where it uses a remote node until the deamon is sunchronised with the network. This would allow to use monero much faster. 
Also the chain should be synched backwards, with the latest block first.

**Comment by taushet** [comment]
I kinda disagree, honestly. The point of the official GUI is to be the core user implementation of the Monero currency, and therefore security should always take precedence. There are many "lighter" wallets in the pipeline (as well as several already released) that will forfeit a small amount of security for convenience and speed. I am not in principle against the ability to connect to a remote node, however to endorse this behaviour to the user while he is syncing in order "allow him to use his monero faster" is not correct.

**Comment by medusadigital** [comment]
this ticket is very old. but the feature request is still present.

im closing this one with the dublicate tag in the favour of this newer ticket: https://github.com/monero-project/monero-core/issues/750

+dublicate

**Comment by danrmiller** [comment]
+duplicate

(spelling)
