### ISSUE TITLE
When running simplewallet with --wallet-file flag, the check whether the file exists is done after asking user for the password

### ISSUE THREAD

**Issue by JollyMort** [monero-project/monero-core#21]
C&p of command prompt below. System: Windows 7 x64. Version: monero.win.x64.v0-9-4-0

I believe it would make sense to check for the file first, before asking the user for the password.

```
C:\monero.win.x64.v0-9-4-0>simplewallet --wallet-file test
Creating the logger system
Monero 'Hydrogen Helix' (v0.9.4.0-release)
Logging at log level 0 to C:\monero.win.x64.v0-9-4-0\simplewallet.log
password: ****
Error: failed to load wallet: file not found "test.keys"
```

**Comment by mbg033** [comment]
Perhaps you want to submit issue here: https://github.com/monero-project/monero/issues

**Comment by JollyMort** [comment]
You're right, I messed up - sorry
