### ISSUE TITLE
Invalid address format in CLI output on launch

### ISSUE THREAD

**Issue by sammy007** [monero-project/monero-core#211]
Version: `26abdee5c47017a80117b1bed5ee36586a240c62`
OS: OSX, qt5: stable 5.7.0 (bottled), HEAD [keg-only]

```
app startd
qrc:///MiddlePanel.qml:259:9: QML StackView: Cannot anchor to an item that isn't a parent or sibling.
2016-Nov-26 18:09:50.460876 Invalid address format
2016-Nov-26 18:09:50.460996 Invalid address format
2016-Nov-26 18:09:50.465505 Invalid address format
```

Starting with empty `~/Monero` directory.
I believe something is wrong with it.

**Comment by moneromooo-monero** [comment]
It starts on the "send" page, so looks whether the send widget has a valid address (and it doesn't, it's empty). That message could be removed though.

**Comment by xmr-eric** [comment]
@sammy007 Can this issue be closed?
