### ISSUE TITLE
New wallet wizard: You will be asked to confirm seed...

### ISSUE THREAD

**Issue by sammy007** [monero-project/monero-core#213]
Never asked. I see only new password and password confirmation prompt and seed is displayed again in the end of new wallet creation dialog.

**Comment by Jaqueeee** [comment]
Not sure what you mean. You can view your seed on last widget page and also on settings page.

**Comment by sammy007** [comment]
There is a promise of seed confirmation in a wizard, but no confirmation.

**Comment by Jaqueeee** [comment]
right. Now i understand. Thanks for pointing out. =)

**Comment by xmr-eric** [comment]
This issue can be closed
