### ISSUE TITLE
Balance and some other controls are not aestetic

### ISSUE THREAD

**Issue by sammy007** [monero-project/monero-core#215]
Will look much better if moved to left a bit since there is a lot of space on left side.

![Balance](https://cdn.pbrd.co/images/2DUfQxwm8.png)

Update: **Tried to reduce font-size here by 1 and it looks good.**

**Comment by sammy007** [comment]
Also tiny space between digits would look perfectly

![](https://cdn.pbrd.co/images/2Eh63AQaV.png)

**Comment by sammy007** [comment]
Also compact view is a bit screwed (Amount).

![](https://cdn.pbrd.co/images/2EL96tsBA.png)

**Comment by sammy007** [comment]
Privacy level "slider" is confusing, it looks more like a progress bar than a slider.

![](https://cdn.pbrd.co/images/2EUSNL3YU.png)

**Comment by sammy007** [comment]
[](https://cdn.pbrd.co/images/3bzilCX94.png)
Checkbox overlap in compact mode on history page.

**Comment by sammy007** [comment]
![](https://cdn.pbrd.co/images/3bDjZgOgI.png)

Labels overlap in compact mode.

**Comment by sammy007** [comment]
![](https://cdn.pbrd.co/images/3bF49v16I.png)

**Comment by sammy007** [comment]
![](https://cdn.pbrd.co/images/85Uu3iK2p.png)

**Comment by xmr-eric** [comment]
@sammy007 Can this issue be closed or if not could it be edited to only the issues that still remain?
