### ISSUE TITLE
RPC rekt on/after "sweep unmixable"

### ISSUE THREAD

**Issue by sammy007** [monero-project/monero-core#218]
Pushed "sweep unmixable" -> "no connection to daemon, Please make sure...".

OS: OSX, monero v0.10.0, monero-core `26abdee`. Daemon is remote.

After I did it first time I even managed to restart `monerod` because `monero-core` failed to get block height on start after this error.

**Comment by Jaqueeee** [comment]
You say daemon is remote but you had to restart `monerod`? So it's your own remote daemon? If so, is it current master? Did you happen to see if the daemon crashed? There has been some reports about segfaults with current monerod master.

**Comment by sammy007** [comment]
Daemon version is 0.10.0 (tag). No it didn't and I see no errors in logs. I just guessed that daemon is not ok and restarted it.

**Comment by Jaqueeee** [comment]
ok. Did you build it yourself or did you use the official binaries?
If you can reproduce the crash/error, lldb debugger might give you some more info

If you're not familiar:
```
lldb monerod
run
(crash)
bt (to get backtrace)
```

**Comment by sammy007** [comment]
I will get back to it tomorrow and will try to reproduce and report. I am compiling both monerod and gui from source.

**Comment by Jaqueeee** [comment]
ok. Thanks.
https://github.com/monero-project/monero/issues/1374 
https://github.com/monero-project/monero/issues/1377

**Comment by sammy007** [comment]
Well it kinda works with monero `master` branch. I can't reproduce node rpc break. Got busy cursor for a while after "No unmixable outputs" and also got "no connection to daemon" a couple of times. I am testing it via wifi, maybe something is wrong with timeout settings if there is a timeout specified on rpc call.

**Comment by medusadigital** [comment]
can this be closed ?

**Comment by medusadigital** [comment]
closing this here until further notice

+resolved
