### ISSUE TITLE
Wizard: Will not load wallet from file if New Account page was visited first

### ISSUE THREAD

**Issue by mochaccinuh** [monero-project/monero-core#223]
Click new account, go back (don't need to finish this wizard). Click "open wallet from file". Open your wallet. It will now start loading the wallet "created" in new account page.

**Comment by Jaqueeee** [comment]
Can not reproduce this. Which platform are you on?

**Comment by mochaccinuh** [comment]
Sure it is loading the wallet you chose in the file manager?

I'm on osx. I have found the bug btw, and have a quick fix for it. It is very strange if this is platform dependent, but you never know. Anyway I can create a pull request and you can see if you want the fix :)

**Comment by Jaqueeee** [comment]
Yes, you're right! Sorry, didn't try hard enough. =)
