### ISSUE TITLE
Rare crash when loading password protected wallet

### ISSUE THREAD

**Issue by mochaccinuh** [monero-project/monero-core#230]
This can happen 1 in 20ish runs on my macbook running osx.

I don't know what is causing this but my best guess is that it has something to do with the async wallet close design. The application will first try to open the wallet with blank password. This fails, async wallet cleanup is initiated (can this be blocked by modal password dialog?), and password dialog gets generated. When correct password is entered the wallet gets loaded, and here the rare crash might occur. If the wallet has no password it will just open it straight away, minimizing risk with far less back and forth logic going on.

**Comment by Jaqueeee** [comment]
It takes a couple of seconds to close a wallet so this error can occur when trying to close a wallet multiple times. Please try #237

**Comment by Jaqueeee** [comment]
Please test #249
