### ISSUE TITLE
Xcode not set up properly

### ISSUE THREAD

**Issue by rpcjacobs** [monero-project/monero-core#231]
Was trying to build the GUI, but kept running into;

`Project ERROR: Xcode not set up properly. You may need to confirm the license agreement by running /usr/bin/xcodebuild.`

As i thought the problem was with my xcode(-upgrade) or the suggested license issue, tried the suggested fix, to no avail. Eventually i completely removed xcode and did a full xcode re-install, without success. Finally made sure `brew` was running properly (`brew doctor`) and that the dependencies where correct, which they where, but still couldn't get passed the error.

In the end i have resolved the issue, by changing a Qt-file,

`$HOME/Qt/5.7/clang_64/mkspecs/features/mac/default_pre.prf`

replacing;
`isEmpty($$list($$system("/usr/bin/xcrun -find xcrun 2>/dev/null")))`

with;
`isEmpty($$list($$system("/usr/bin/xcrun -find xcodebuild 2>/dev/null")))`

as per; http://stackoverflow.com/a/35098040/1683164

Hopefully it can help others, with the same issue. Might also be a good addition to the install-guide.

**Comment by dternyak** [comment]
Can confirm this fix is required on macOs 10.11 and 10.12

**Comment by Jaqueeee** [comment]
Thanks. Added this to readme in #231

**Comment by dternyak** [comment]
@Jaqueeee You mean https://github.com/monero-project/monero-core/pull/241

**Comment by Jaqueeee** [comment]
@dternyak Thanks. Updated.
