### ISSUE TITLE
Selected language not persisted on MacOS

### ISSUE THREAD

**Issue by maitscha** [monero-project/monero-core#246]
Selecting a language in the language wizard page is not persisted on MacOS (tested with 10.11.6). The Qt settings are persisted in the MacOS user `defaults` with the domain `org.getmonero.monero-core`:

```
$ defaults read org.getmonero.monero-core
{
    ...
    locale = "en_US";
}
```

If I open the UI, change the language to German, and close the UI, the `locale` value is still `en_US`. Manually changing the `locale` value to `de` has the desired effect:

```
$ defaults write org.getmonero.monero-core locale de
```

The UI now uses the German translations.

This bug has also been reported in #164

**Comment by xmr-eric** [comment]
@maitscha Can this issue be closed?
