### ISSUE TITLE
Shell does not terminate automatically when monero-core is closed

### ISSUE THREAD

**Issue by medusadigital** [monero-project/monero-core#25]
if monero-core gets closed, shell doesnt terminate and stays showing the monero-core log, until exited the hard way with ctrl+q. this was different before if i remember correctly

--> Ubuntu 16.04 on mainnet together with pull request #23

**Comment by radfish** [comment]
Could you elaborate please? The shell you ran ./monero-core in? Why would it close when a process exits?

**Comment by medusadigital** [comment]
im sorry maybe its the language. im not expecting the window i ran ./monero-core inside to close. 
but i expect the shell to return to normal usable state after gui gets closed. this doesnt happen anymore.

right now the shell i launched from looks like this after i closed the GUI:
![shellcloseist](https://cloud.githubusercontent.com/assets/17108301/18731441/32cc00f0-805c-11e6-95e6-d2be1d836b37.jpg)

But i would expect something like that:

![shellclosesoll](https://cloud.githubusercontent.com/assets/17108301/18731446/41cea076-805c-11e6-8748-e6e5650af51f.jpg)


Nevertheless i dindt see the process running anymore, so the process gets killed correctly it seems...part of why i somehow cant understand this beahviour.

**Comment by medusadigital** [comment]
tested together with fresh monero-core build from /mbg033/monero-core, branch=develop on OS Ubuntu 16.04

works perfectly ---> closed
