### ISSUE TITLE
GUI styling is broken in compact mode

### ISSUE THREAD

**Issue by xmr-eric** [monero-project/monero-core#252]
Tool may work fine, but I think messing with the title bar messed up some stuff. 

See: https://i.imgur.com/ht6LEif.png

**Comment by xmr-eric** [comment]
This is on OSX 10.12.1

**Comment by M5M400** [comment]
confirmed on ubuntu 16.04 x64 on ff998ba

Also I have standard window decorations now *sigh*

![screenshot from 2016-12-09 15-15-57](https://cloud.githubusercontent.com/assets/22886679/21051856/669307f4-be22-11e6-963b-01b8e1e9ed8b.png)

![screenshot from 2016-12-09 15-15-44](https://cloud.githubusercontent.com/assets/22886679/21051862/6a8d9720-be22-11e6-8157-d4c29a124ab3.png)

**Comment by moneromooo-monero** [comment]
Broken by https://github.com/monero-project/monero-core/pull/238/commits/17add2d75e36b5f9f224d2234db55dc9c68f7fee, but I don't know what this fixed in the first place, so I don't want to revert this right now.

**Comment by M5M400** [comment]
how is this closed if it's not merged to master yet?

**Comment by xmr-eric** [comment]
Good point. I'll keep it open for now.
