### ISSUE TITLE
Settings page needs fixing when in compact mode

### ISSUE THREAD

**Issue by xmr-eric** [monero-project/monero-core#277]
Buttons and text cut off

![screen shot 2016-12-13 at 8 34 55 pm](https://cloud.githubusercontent.com/assets/21302237/21166502/f5b528f0-c173-11e6-8273-89a1746c6b72.png)

**Comment by M5M400** [comment]
or maybe consider only allowing send/receive tabs in compact mode?

**Comment by xmr-eric** [comment]
Fixed in #385
