### ISSUE TITLE
validation missing if transaction amount = balance

### ISSUE THREAD

**Issue by medusadigital** [monero-project/monero-core#28]
if i try to send a transaction with the amount exactly matching my balance, it looks like this: 

![mainnet_send2_testdevdonationfail](https://cloud.githubusercontent.com/assets/17108301/18679636/d17c02f6-7f60-11e6-8e91-bbcbfe151fde.jpg)

- Confirmation message is wrong
- transaction should get rejected with "not enough money" reject message

after i pressed ok, nothing happend.

--> Ubuntu 16.04 on mainnet together with pull request #23

**Comment by Jaqueeee** [comment]
How about this one? Wasn't able to reproduce. Already solved?

**Comment by medusadigital** [comment]
fixed --> works ---> closed

**Comment by medusadigital** [comment]
all fine
