### ISSUE TITLE
Daemon not initializing testnet when option is selected

### ISSUE THREAD

**Issue by xmr-eric** [monero-project/monero-core#280]
Creating a testnet wallet and starting the daemon starts it on mainnet

**Comment by Jaqueeee** [comment]
You can forward cli arguments to the daemon if you start GUI from terminal
On mac: 
./monero-core.app/Contents/MacOS/monero-core --testnet

**Comment by xmr-eric** [comment]
If there's a checkbox that says "testnet" on wallet creation, would it be possible to automatically start the daemon in testnet mode when that wallet is loaded?

**Comment by Jaqueeee** [comment]
yes, it's possible, but since the daemon isn't killed when switching wallets there could be an issue when switching between testnet and mainnet.  Not sure what's best.

**Comment by medusadigital** [comment]
can this be closed ? 

AFAIk testnet flag is not needed anymore now.

**Comment by medusadigital** [comment]
+resolved
