### ISSUE TITLE
Stronger Password Suggestions

### ISSUE THREAD

**Issue by SamsungGalaxyPlayer** [monero-project/monero-core#281]
The Monero GUI falls a little short when suggesting the strength of passwords. A 4 character password is considered "medium". Luckily, it takes 20 characters to get to "high".

The Monero wallet is a service that many people will keep substantial money in. The GUI should give stricter suggestions for passwords. I suggest the minimum for a "moderate" password should be 10 characters. I'd argue it should stay on the lowest setting if the password is less than 5 characters.

http://imgur.com/a/zCpam

**Comment by dEBRUYNE-1** [comment]
Duplicate of #1.

**Comment by moneromooo-monero** [comment]
https://github.com/monero-project/monero-core/pull/292
