### ISSUE TITLE
Automatic dev donation not working on mainnet

### ISSUE THREAD

**Issue by medusadigital** [monero-project/monero-core#29]
When sending a transaction with monero-core on mainnet, the dev donation is not sent out, even if enabled. 
![nodevdonation](https://cloud.githubusercontent.com/assets/17108301/18679772/57f08f8c-7f61-11e6-9113-d55782f04fa6.jpg)

i sent 1.5 xmr from monero-core ubuntu to my simplewallet on windows.

1.0 and 0.5 is my transaction
0.09 and 0.4 is my change

the dev donation is missing, which is configured for 50% of the transaction fee (in this example that would be 0.005)

--> Ubuntu 16.04 on mainnet together with pull request #23

**Comment by Jaqueeee** [comment]
no implemented yet. Removed page in https://github.com/monero-project/monero-core/pull/93

**Comment by medusadigital** [comment]
feature disabled for now ---> closed
