### ISSUE TITLE
Latest build doesn't detect connected daemon

### ISSUE THREAD

**Issue by xmr-eric** [monero-project/monero-core#290]
If I log in, the daemon starts but the GUI shows that it's disconnected. If I click "Start Daemon", the Initializing Daemon window pops up and just spins. If I look at the Daemon Log, it shows that it tried starting the daemon a second time, even though it's already running, so that's why starting it failed.

![screen shot 2016-12-15 at 3 21 22 pm](https://cloud.githubusercontent.com/assets/21302237/21240810/e418708a-c2da-11e6-8c79-1d44908b41b1.png)

In picture above, you can see the daemon log shows the daemon has connected, but the GUI in the bottom left still says Disconnected. (OSX 10.12.2)

**Comment by Jaqueeee** [comment]
https://github.com/monero-project/monero-core/pull/291
