### ISSUE TITLE
GUI is too tall for many displays

### ISSUE THREAD

**Issue by xmr-eric** [monero-project/monero-core#296]
Eg: too tall for 1366x768

![capture](https://cloud.githubusercontent.com/assets/21302237/21275785/63cd8236-c39c-11e6-818b-f3ffb4fddffa.png)

**Comment by xmr-eric** [comment]
Looks to me that the navigation bar on the left could be shrunk 10%. Perhaps could integrate this fix into adding a smaller icon-only nav bar on Compact Mode, which would fix #221

**Comment by moneromooo-monero** [comment]
Item height is now decreased somewhat, plus new submenus decreasing the maximum extent by one item with current setup.

**Comment by Jaqueeee** [comment]
@xmr-eric still to tall for your screen?
