### ISSUE TITLE
Language selection not skipped when wallet is closed from settings page

### ISSUE THREAD

**Issue by ClementJnc** [monero-project/monero-core#310]
When there is only one language accepted (as now), the GUI opens the Wizard directly to the optionsPage ("Create"/"Recover"/"Open") rather than to the welcomePage (language choice). It works also like that when the user cancels the opening of the last wallet from the pop-up window. However if the user clicks on "Close wallet" in the setting, he goes to the welcomePage instead of the optionPage I would expect.

**Comment by medusadigital** [comment]
seems solved to me now that there are more languages.

can you confirm?

**Comment by dEBRUYNE-1** [comment]
+resolved
