### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by banjochose** [monero-project/monero-core#325]
There is build error  for Ubuntu 14
and Debian as well.

I am going to upgrade Ubuntu to 16 and it will solve it for me but it would be easier for other if it would work for those platforms as well.

**Comment by xmr-eric** [comment]
Can you give the error? If it's a lot of text, feel free to paste it into https://paste.fedoraproject.org/

**Comment by banjochose** [comment]
Alright so not even Ubuntu 16 upgrade helped 

https://paste.fedoraproject.org/510712/14823577/

**Comment by banjochose** [comment]
Also why there aren't any GUI-qt binaries ? For moneroj to gain on value it need to be noob friendly and noobs need's gui the most.

**Comment by Jaqueeee** [comment]
can you try #330?

**Comment by banjochose** [comment]
nope it did not solved it, still the same

**Comment by Jaqueeee** [comment]
ok. can you try uninstalling libunwind? 
btw. there are binaries now if you haven't noticed. :)

**Comment by banjochose** [comment]
New GUI wallet looks real fancy, I like it. I got it from the binaries but build is still unsuccessful even after purging libunwind-dev

**Comment by banjochose** [comment]
Are you in position to spread the message about new GUI to the press (bitcoin news like websites) ?
Perhaps pay some freelancer to write an article or so ?

Thinking to buy some more coins as the gui has value and does ease use of wallet for noobs.

**Comment by xmr-eric** [comment]
@banjochose Is this still an issue?

**Comment by dEBRUYNE-1** [comment]
+resolved
