### ISSUE TITLE
"Remove from history" icon appearing on every page

### ISSUE THREAD

**Issue by xmr-eric** [monero-project/monero-core#327]
First appeared when I clicked on History:

![screen shot 2016-12-21 at 1 17 08 pm](https://cloud.githubusercontent.com/assets/21302237/21401285/c01a2d62-c781-11e6-8185-ab1188ef304a.png)

Then began appearing on every page:

![screen shot 2016-12-21 at 1 17 36 pm](https://cloud.githubusercontent.com/assets/21302237/21401266/aadda582-c781-11e6-8c32-7d96b49593cb.png)
![screen shot 2016-12-21 at 1 18 23 pm](https://cloud.githubusercontent.com/assets/21302237/21401269/b129bdae-c781-11e6-8708-150885d4a357.png)
![screen shot 2016-12-21 at 1 18 40 pm](https://cloud.githubusercontent.com/assets/21302237/21401272/b3adabd0-c781-11e6-946e-c64836956434.png)

**Comment by Jaqueeee** [comment]
@xmr-eric was this an one time issue or can you reproduce it? I couldn't. 
"remove from history" should be changed to "remove from address book" anyway. 
/Jacob

**Comment by xmr-eric** [comment]
I can't reproduce it either :)

**Comment by Jaqueeee** [comment]
actually i did reproduce it now. =)
