### ISSUE TITLE
OpenSuSE 42.2: crash when using bundled libs, works fine with system libs

### ISSUE THREAD

**Issue by villabacho** [monero-project/monero-core#333]
The Monero Core GUI Beta 1 crashed on my OpenSuSE 42.2 system when using the bundled libraries. When using system libraries instead, except for libicudata.so.55, libicui18n.so.55, and libicuuc.so.55 (which I didn't get from the OpenSuSE default repositories), it works fine.

**Comment by villabacho** [comment]
I should add that the crash with the bundled libs already happens during startup. Even gdb crashed when having the bundled libs in my LD_LIBRARY_PATH, so I guess it happens already when loading/initializing one of the libraries.

**Comment by peronero** [comment]
Issue exists on Tumbleweed as well.

**Comment by xmr-eric** [comment]
@villabacho Can this issue be closed?

**Comment by peronero** [comment]
Was resolved on Tumbleweed.

**Comment by villabacho** [comment]
@xmr-eric yes, that happened wit beta 1. beta 2 runs fine for me.
