### ISSUE TITLE
Win64 Wallet Crashes Not Usable

### ISSUE THREAD

**Issue by allegro101** [monero-project/monero-core#334]
GUI Wizard crashes when asked to open a wallet from file. Never given the chance to specify the file. 

If using the wizard to create a new wallet the wallet is created but program crashes when the Use Monero button is clicked.

**Comment by relics219** [comment]
I'm using the x64 wallet and it's not crashing for me at that point. Maybe check another computer?

**Comment by Jaqueeee** [comment]
@allegro101 
Can you start cmd.exe and run the wallet in there? 
```
cd <your gui location>
monero-wallet-gui.exe > log.txt 
```
Hopefully it will give us some debug info in log.txt

**Comment by allegro101** [comment]
Jaqueeee I can run the wallet from the command window but when I use the 'open wallet from file' option GUI quits with error msg that GUI has stopped working. For some reason I cannot get any debug information saved to a log file. Wish I could provide more help.

**Comment by Jaqueeee** [comment]
ok. It would help a lot if you could download GDB debugger and start gui with that. 
from cmd:
```
gdb monero-wallet-gui.exe
(gdb) run
```
after crash you can type `thread apply all bt full` to get the stack trace. Copy that info to https://paste.fedoraproject.org and link here.

**Comment by allegro101** [comment]
Sorry have not been able to decipher using gdb perhaps someone else with the same problem can contribute.

**Comment by medusadigital** [comment]
@allegro101 you can use like this:

- open gdb
- "target exec C:\path\to\bins\monero-wallet-gui.exe"
-  "run"

**Comment by Jaqueeee** [comment]
@allegro101  Please also try using the software renderer described here:
http://monero.stackexchange.com/questions/2928/how-to-change-the-monero-core-rendering-mode-for-older-computers/2929#2929

**Comment by allegro101** [comment]
Problem solved. deBRUYNE posted a fix at /r/Monero that is directed at older computers but solved the problem on my new one details at [this link](https://www.reddit.com/r/Monero/comments/5jwteb/psa_if_the_beta_gui_is_not_working_on_your/)
