### ISSUE TITLE
Wallet creates $USER directory name in $USERs root by default (macOs)

### ISSUE THREAD

**Issue by dternyak** [monero-project/monero-core#337]
Instead of `/Users/first-last/monero/mywallet.keys` as expected, the GUI creates `/Users/first-last/first-last/mywallet.keys`

**Comment by Jaqueeee** [comment]
cannot reproduce this. Does it also say this path on the create wallet page in wizard?

**Comment by Jaqueeee** [comment]
does your first or lastname include any non-ascii characters btw?

**Comment by dternyak** [comment]
It does not - and the wallet path on the wizard create page claimed it would create `/Users/first-last/monero`

**Comment by Jaqueeee** [comment]
ok. The expected default path is actually `/Users/$userName/Monero/wallets/$walletName/$walletName.keys`
if you don't change the $walletName when you create the wallet it would be the same as $userName.  
But in your case the monero and wallets folders never gets created?
Trying to reproduce this. Do you have a space between first and last?

**Comment by dternyak** [comment]
Exactly. no space. 

Very strange that we're not getting the same results!

**Comment by Jaqueeee** [comment]
Could you try running the wallet in terminal and paste the log when creating a wallet?
To start gui in terminal:
`./monero-wallet-gui.app/Contents/MacOS/monero-wallet-gui`

**Comment by dternyak** [comment]
@Jaqueeee Now it creates at the correct location - /Users/first-last/Monero/wallets/wallet-name.

Since I can't even reproduce myself, I'm going to close this.

**Comment by Jaqueeee** [comment]
OK. Too bad. Maybe we'll never get the answer to what happened! ;)

**Comment by dternyak** [comment]
@Jaqueeee Hehe I am almost positive I did not mess with the wallet default because I was so eager to play with the beta! But maybe I did, and maybe that was the cause.
