### ISSUE TITLE
Clicking red continue button on recover wallet screen hangs (macOS)

### ISSUE THREAD

**Issue by dternyak** [monero-project/monero-core#339]
Nothing happens when attempting to recover a wallet via mnemonic after inputting the seed and clicking the red continue button.

**Comment by dternyak** [comment]
This happens only when the mnemoic is correct in that it has the correct number of words, but contains a typo / an incorrect word.

**Comment by Jaqueeee** [comment]
related to https://github.com/monero-project/monero-core/issues/331

**Comment by dternyak** [comment]
@Jaqueeee Thanks - closing.
