### ISSUE TITLE
api-ms-win-core-heap-l1-2-0.dll is Missing

### ISSUE THREAD

**Issue by medusadigital** [monero-project/monero-core#340]
api-ms-win-core-heap-l1-2-0.dll is Missing.

reports from windows 8, and win 7 enterprise : https://www.reddit.com/r/Monero/comments/5jr7r4/monero_core_gui_beta_1_released/dbietd2/

**Comment by Jaqueeee** [comment]
Solved by using the software renderer http://monero.stackexchange.com/questions/2928/how-to-change-the-monero-core-rendering-mode-for-older-computers/2929#2929

**Comment by medusadigital** [comment]
great! 

--> closed
