### ISSUE TITLE
GUI password strength meter turns green but meter not moved to "high" when pasting long password

### ISSUE THREAD

**Issue by taky2** [monero-project/monero-core#341]
There seems to be some character threshold here where when pasting in a long password the strength meter does not move, but it turns green. 

After some testing I have discovered that anything over 18 characters the bar/meter will turn green but not move to the full position (when pasting a new password on the creation screen) 

Here is a picture:
![image](https://cloud.githubusercontent.com/assets/7447137/21438391/d88b6ab8-c845-11e6-93d4-0bb957507f8e.png)

(I am using the mac version)

**Comment by moneromooo-monero** [comment]
If you type more, does it never move ?

**Comment by taky2** [comment]
Revisiting this, I am having some issues with consistency testing it. 

Under specific circumstances: 

There actually seems like there might be some variance. Pasting 19 or 20 characters (only letters and numbers) will currently update the strength meter correctly.

22 characters the issue still exists.
21 characters the strength bar updates correctly.

With 22 characters typing additional characters does not update the status bar. Deleting 1 character WILL update it. It appears this is an issue for any number of character greater than 21, while 21 or less characters works fine. 

The OP refers to passwords with special characters. As I am testing this, I am realizing that when symbols are involved, the bug occurs with at a lower character threshold. This threshold might have some variance depending on the special characters involved. 

However, testing right now with special characters appears to be reliably working with 20 or less characters as well. IDK why I thought 18 was previously the threshold.

Currently when using a password over 20 characters (including symbols) adding additional characters will not move the strength meter. When deleting characters it will not move until there are 20 characters or less. Furthermore, if there are 18 or 19 characters and one or two are added (by typing) it will update the meter bar.

**Comment by moneromooo-monero** [comment]
Since you're mentioning length of the password a lot, beware that if you type aaaaaaaaaaaaaaaaaaa, the strength of the password will not increase much at all even if you type 200 a, since crackers will try repeated things.

**Comment by medusadigital** [comment]
sounds similar: https://www.reddit.com/r/Monero/comments/5jr7r4/monero_core_gui_beta_1_released/dbjojiv/

**Comment by taky2** [comment]
I am using a randomized password generator. I am not testing with intentional consecutive characters.

**Comment by moneromooo-monero** [comment]
Thanks for the report, fixed in https://github.com/monero-project/monero-core/pull/359

**Comment by xmr-eric** [comment]
@taky2 Can this issue be closed?

**Comment by taky2** [comment]
@xmr-eric not sure, I only see the original beta for download still, hence I haven't been doing any further testing. I see something released 10 hrs ago, but it looks like it needs to be built from source.

**Comment by medusadigital** [comment]
GUI beta 2 is out with fix included.

i thik this can be closed

**Comment by dEBRUYNE-1** [comment]
+resolved
