### ISSUE TITLE
Issues on high DPI screens

### ISSUE THREAD

**Issue by Jaqueeee** [monero-project/monero-core#343]
resolution: 3840x2160

![image](https://cloud.githubusercontent.com/assets/5909557/21440277/812b36b6-c892-11e6-9f42-ff1fa8736239.jpg)

elements without fixed pixels looks ok:
![image 1](https://cloud.githubusercontent.com/assets/5909557/21440298/a1d2eaee-c892-11e6-92af-ae5db169d3fd.jpg)

Reported by N-rG

**Comment by rlittlefield** [comment]
Can confirm on surface book (~271 DPI, 3000x2000)

**Comment by taoteh1221** [comment]
Same on 4k res on win10.

**Comment by Jaqueeee** [comment]
hi @rlittlefield and @taoteh1221 
Can you try if PR #514 solves this?
Windows binary:
https://build.getmonero.org/downloads/monero-core-f094ffc-win64.zip
Linux:
https://build.getmonero.org/downloads/monero-core-f094ffc-linux-amd64.tar.gz

**Comment by rlittlefield** [comment]
I've tested the windows binary you linked, and it works great. I might recommend an adjustment to the "network status" area to prevent it from overlapping when the "advanced" accordion is open. I don't know if this affects other DPIs.

![monero-overlap](https://cloud.githubusercontent.com/assets/290970/23470734/6b49dbce-fe64-11e6-9749-4c887b038baf.PNG)

**Comment by medusadigital** [comment]
Hei @rlittlefield , unfortunately we needd to make the defualt size that small becasue of mac users. but you should be able to extend the window on the bottom right corner, which will prevetnt the overlap

**Comment by rlittlefield** [comment]
Yeah, that was just a suggestion. Potentially the accordion could be scrollable? It is easy enough to solve I don't think it is a big issue.

**Comment by rlittlefield** [comment]
Thanks for the fix!

**Comment by Jaqueeee** [comment]
@rlittlefield you're welcome. Thanks for testing. Will fix the the overlapping left menu one day. Probably gonna need to add scrolling to the mobile version anyway.

**Comment by amiuhle** [comment]
Don't know if it's related, but I thought I'll just reuse this issue since it's still open. This is my wallet on a 3200x1800 resolution on a 13" screen on Ubuntu 16.10. Built from b757cc28b8055c7811769c80fcbda569a66750d7

Also, no asterisks are shown in the password prompt.

![screenshot from 2017-03-11 17-41-01](https://cloud.githubusercontent.com/assets/460091/23825214/f6bb0952-0685-11e7-9356-b22cece734e1.png)

**Comment by dEBRUYNE-1** [comment]
+resolved
