### ISSUE TITLE
New wallet synchronizing, but network status "Disconnected"

### ISSUE THREAD

**Issue by peanutsformonkeys** [monero-project/monero-core#344]
With today's released [beta](https://getmonero.org/2016/12/22/monero-core-gui-beta-released.html), I created a new wallet. While the wallet is synchronizing with the (local) daemon, the network status still shows "**Disconnected**". Afterwards, the network status updates to "Connected". It seems that the network status is not updated at the right time, because synchronizing without connection seems impossible to me?

![monero-wallet-gui beta disconnected](https://cloud.githubusercontent.com/assets/21346321/21441753/0a0f080c-c89a-11e6-83fa-1a7f826e7111.png)

**Comment by medusadigital** [comment]
that should be solved in Beta 2  AFAIK

**Comment by peanutsformonkeys** [comment]
Indeed, Beta 2 shows "Synchronizing" as Network status right from the start.
