### ISSUE TITLE
Feature request: allow saving QR-code image

### ISSUE THREAD

**Issue by peanutsformonkeys** [monero-project/monero-core#346]
When updating a [Stack Exchange question on QR-codes](https://monero.stackexchange.com/questions/2008/how-do-i-generate-a-qr-code-for-a-monero-address/3076#3076), I hoped I could save the QR-code from the Monero Core GUI's Receive page by **right-clicking on the image**, but that didn't do anything. I think it would be useful if one could save the image this way to distribute further.

**Comment by sir-pinecone** [comment]
@peanutsformonkeys this has been implemented :) you can close this issue now.

**Comment by peanutsformonkeys** [comment]
Right-click and saving works great, just tested on Windows. Thanks!
