### ISSUE TITLE
LibGL driver errors

### ISSUE THREAD

**Issue by abelboldu** [monero-project/monero-core#347]
The LibGL library reports errors:
```
% ./start-gui.sh 
app startd
libGL error: unable to load driver: i965_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: i965
libGL error: unable to load driver: i965_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: i965
libGL error: unable to load driver: swrast_dri.so
libGL error: failed to load driver: swrast
Unrecognized OpenGL version
Unrecognized OpenGL version
```
so the GUI can't load.

Workaround: Removing the libs/libGL.so.1 file fixes the problem.

OS : Void Linux
Linux tdn 4.9.0_3 #1 SMP PREEMPT Wed Dec 21 16:16:39 UTC 2016 x86_64 GNU/Linux

**Comment by Fornax96** [comment]
Having the same problem on Ubuntu 16.10. Deleting libGL.so.1 fixed it.

**Comment by Jaqueeee** [comment]
@Fornax96 You had this issue with Beta2?

**Comment by Jaqueeee** [comment]
I guess not, since that file isn't included in Beta2.

**Comment by Fornax96** [comment]
I'll check. I got this version from the monero website, I guess it's outdated?

**Comment by Fornax96** [comment]
Beta 2 starts without deleting any files :)

**Comment by medusadigital** [comment]
can be closed

**Comment by dEBRUYNE-1** [comment]
+resolved
