### ISSUE TITLE
Daemon not compatible with GUI

### ISSUE THREAD

**Issue by jsnfwlr** [monero-project/monero-core#348]
![oops](https://cloud.githubusercontent.com/assets/1097895/21446500/d459cae0-c901-11e6-99a5-7a49f0164a51.png)

Freshly downloaded, machine has never had any monero daemon installed on it ... the daemon is the one that was in the same zip as the GUI ...

**Comment by xmr-eric** [comment]
What versions are listed on the settings page for the GUI and daemon?

**Comment by jsnfwlr** [comment]
Unfortunately I can't get to the settings page because it crashes immediately after showing this error

**Comment by medusadigital** [comment]
what platform is this ?

**Comment by jsnfwlr** [comment]
odd ... when I run it with the > log.txt at the end, it works fine ...

**Comment by jsnfwlr** [comment]
Actually, no ... it only worked because I got my password wrong ... odd 

2016-Dec-23 19:10:13.344081 ERROR C:/msys64/home/vagrant/slave/monero-core-win64/build/monero/contrib/epee/include/storages/portable_storage.h:161 portable_storage: wrong binary format - signature missmatch
2016-Dec-23 19:10:13.344581 ERROR C:/msys64/home/vagrant/slave/monero-core-win64/build/monero/src/wallet/wallet2.cpp:1959 !r. THROW EXCEPTION: error::invalid_password
2016-Dec-23 19:10:13.344581 C:/msys64/home/vagrant/slave/monero-core-win64/build/monero/src/wallet/wallet2.cpp:1959:N5tools5error16invalid_passwordE: invalid password
2016-Dec-23 19:10:13.345081 ERROR C:/msys64/home/vagrant/slave/monero-core-win64/build/monero/src/wallet/api/wallet.cpp:298 Error opening wallet: invalid password
2016-Dec-23 19:10:13.557108 ~WalletImpl
2016-Dec-23 19:10:13.557108 closing wallet...
2016-Dec-23 19:10:13.557108 wallet::store done
2016-Dec-23 19:10:13.557108 Calling wallet::stop...
2016-Dec-23 19:10:13.557108 wallet::stop done

**Comment by BoscoMurray** [comment]
I saw the same error but only for a second, then the error vanished and the daemon started syncing. I used the downloaded binaries on a fresh install of Ubuntu 16.04, 2 vCPU, 8GB RAM in a VirtualBox VM on an i5 laptop with decent SSD.

**Comment by jsnfwlr** [comment]
Well it's working perfectly now.

**Comment by Jaqueeee** [comment]
@BoscoMurray the error above is nothing to worry about. It's just the wallets way of saying that the password was wrong. If you have a wallet with password that error is always shown because it tries to open the wallet without a password first.

**Comment by BoscoMurray** [comment]
I didn't get my password wrong. It's like the wallet was too quick to think there was an issue and threw up this error, then cleared the error itself. No biggie, just a UX thing.

**Comment by Jaqueeee** [comment]
Not saying you got it wrong. But the GUI always tries to open the last opened wallet on startup, and if it is password protected it will throw this error.

**Comment by BoscoMurray** [comment]
Yup. I know it's trivial for a dev, but is it not worth changing its behaviour for a better UX?

**Comment by Jaqueeee** [comment]
ah. I think we're talking about different things here. I was referring to the error in the log. =)
We should definitely fix the issue that causes the GUI to report the daemon isnt compatible. If we can reproduce it somehow.
