### ISSUE TITLE
Mac: Files in an odd location

### ISSUE THREAD

**Issue by SilverPin** [monero-project/monero-core#350]
Not a big problem, but the location that the GUI installs its files on OSX is quite odd. It took me.a while to find before I realised they were right in front of my eyes.

At the minute the app files are stored at:

> /users/[name]

Usually apps would store their information in a hidden folder at: 

> /users/[name]/library/application support

**Comment by medusadigital** [comment]
the config File is located in: $HOME/Library/Preferences/org.getmonero.monero-core.plist

wallets get created in /users/xxx/Monero/wallets

**Comment by SilverPin** [comment]
I see. Thanks!

**Comment by Jaqueeee** [comment]
Can this be closed @SilverPin?
