### ISSUE TITLE
Increase Custom Daemon line width on Wizard Options page

### ISSUE THREAD

**Issue by xmr-eric** [monero-project/monero-core#352]
Runs out of space so "(optional)" has fallen to a second line. Hopefully a quick fix.

Note: I don't have this problem on OSX, but I do on Win10 64

![monero-wallet-1f433b](https://cloud.githubusercontent.com/assets/21302237/21462727/5deca676-c92d-11e6-97ad-a5d3d67b9ee5.png)

**Comment by Jaqueeee** [comment]
Never been able to reproduce this but #496 should fix it anyway.
