### ISSUE TITLE
Horizontally center Wizard titles

### ISSUE THREAD

**Issue by xmr-eric** [monero-project/monero-core#353]
"Give your wallet a name" "Give your wallet a password" are all off center, perhaps because of the progress bullets to their right. If possible, these should be horizontally center.

![monero-wallet-4d976a](https://cloud.githubusercontent.com/assets/21302237/21462771/e4f27c22-c92d-11e6-884b-2d3de3b10610.png)

**Comment by Jaqueeee** [comment]
Fixed in #496
