### ISSUE TITLE
Password kept when using Recovery wizard and then Creation wizard

### ISSUE THREAD

**Issue by ClementJnc** [monero-project/monero-core#356]
Reproduction steps:
1. Start the recovery of a wallet
2. Enter the private key
3. Enter a password 
4. Go back to the Welcome page
5. Start the creation of a wallet
6. Pass the mnemonic step
The password is already filled in (in both fields). If you delete the confirmation field and retype the password entered at step 3, you notice it is the same.

**Comment by medusadigital** [comment]
reproducible with GUI Beta 1

**Comment by medusadigital** [comment]
same with GUI Beta 2
