### ISSUE TITLE
version.js not found (git rev-list issue in monero/src/version.cmake?)

### ISSUE THREAD

**Issue by voidzero** [monero-project/monero-core#360]
Trying to build this on Gentoo x64, but getting an error that version.js isn't found. Probably related to the following, that is shown when `./get_libwallet_api.sh` is executed. It suggests that `git rev-list` isn't executed correctly by monero/src/version.cmake:

```
make[3]: Entering directory '/foobar/monero-core/monero/build/release'
[100%] Generating version/version.h
-- You are currently on commit dd580d7
usage: git rev-list [OPTION] <commit-id>... [ -- paths... ]
  limiting output:
    --max-count=<n>
    --max-age=<epoch>
    --min-age=<epoch>
    --sparse
    --no-merges
    --min-parents=<n>
    --no-min-parents
    --max-parents=<n>
    --no-max-parents
    --remove-empty
    --all
    --branches
    --tags
    --remotes
    --stdin
    --quiet
  ordering output:
    --topo-order
    --date-order
    --reverse
  formatting output:
    --parents
    --children
    --objects | --objects-edge
    --unpacked
    --header | --pretty
    --abbrev=<n> | --no-abbrev
    --abbrev-commit
    --left-right
    --count
  special purpose:
    --bisect
    --bisect-vars
    --bisect-all
CMake Warning at src/version.cmake:47 (message):
  Cannot determine most recent tag.  Make sure that you are building either
  from a Git working tree or from a source archive.

```

When running `qmake` from qt5:

```
% /usr/lib/qt5/bin/qmake
Project MESSAGE: Building with libunwind
RCC: Error in 'qml.qrc': Cannot find file 'version.js'
```

**Comment by Jaqueeee** [comment]
Run build.sh instead of qmake

**Comment by moneromooo-monero** [comment]
Does it work if you add "HEAD" after "--abbrev-commit" in src/version.cmake ?
This is the curent full line:
        execute_process(COMMAND "${GIT}" rev-list --tags --max-count=1 --abbrev-commit RESULT_VARIABLE RET OUTPUT_VARIABLE TAGGEDCOMMIT OUTPUT_STRIP_TRAILING_WHITESPACE)
and I'm asking about it being:
        execute_process(COMMAND "${GIT}" rev-list --tags --max-count=1 --abbrev-commit HEAD RESULT_VARIABLE RET OUTPUT_VARIABLE TAGGEDCOMMIT OUTPUT_STRIP_TRAILING_WHITESPACE)

**Comment by moneromooo-monero** [comment]
What is the output of this command, when you're in the monero tree ?

git rev-list --tags --max-count=1 --abbrev-commit

Then this one:

git show --oneline

**Comment by voidzero** [comment]
The first command gives me the same usage output. The second shows me a loong output, too long to post, 471507 lines! Full of diffs.

I think we need to pass a commit-id to git rev-list:

```
% git rev-list --tags --max-count=1 --abbrev-commit HEAD
dd580d7
```

The `git rev-parse` command might be a usable alternative:

```
% git rev-parse --abbrev-ref HEAD
master

% git rev-parse --short master     
dd580d7

```
```

**Comment by voidzero** [comment]
@Jaqueeee build.sh doesn't help me much either, even after I corrected the path to qmake, I get the same usage output from `git rev-list` and after a few other lines, I get:

```
g++ -c -pipe -O2 -std=gnu++0x -Wall -W -D_REENTRANT -fPIC -DQT_NO_DEBUG -DQT_QUICK_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I../../monero-core -I. -I/mnt/coindb/src/monero-core/monero/include -I../src/libwalletqt -I../src/QR-Code-generator -I../src -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtQuick -isystem /usr/include/qt5/QtWidgets -isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtQml -isystem /usr/include/qt5/QtNetwork -isystem /usr/include/qt5/QtCore -I. -I/usr/lib64/qt5/mkspecs/linux-g++ -o main.o ../main.cpp
In file included from ../main.cpp:39:0:
../src/libwalletqt/WalletManager.h:6:32: fatal error: wallet/wallet2_api.h: No such file or directory
```

**Comment by moneromooo-monero** [comment]
What is the output of:

git --version

**Comment by moneromooo-monero** [comment]
Did you clone a shallow repo (ie, --depth 1) ?

**Comment by moneromooo-monero** [comment]
What is the output of:

git tag

**Comment by voidzero** [comment]
```
% git --version
git version 2.7.3

% git tag
v0.0-beta-1
```

Not a shallow clone.

**Comment by voidzero** [comment]
That tag is from monero-core, btw.

**Comment by moneromooo-monero** [comment]
Works here (with a test repo) with git 2.7.3.
I'll have to ignore this then, unless/until new information.

**Comment by Jaqueeee** [comment]
@voidzero Can you post your full output from get_libwallet_api.sh and build.sh? Preferably on https://paste.fedoraproject.org or similar.

**Comment by voidzero** [comment]
sure. Here's build.sh:
https://paste.fedoraproject.org/513848/48287037/

Here's get_libwallet_api.sh:
https://paste.fedoraproject.org/513850/48287041/

Both links will expire in one month.

**Comment by Jaqueeee** [comment]
@voidzero 
Sorry, I meant the output you get when running those scripts.

**Comment by voidzero** [comment]
@moneromooo-monero what are the contents of a correctly generated version.js? I will add it manually so that I can at least try to continue building the gui.

**Comment by voidzero** [comment]
@Jaqueeee Oh, the output :smile: Alright, will post tomorrow.

**Comment by moneromooo-monero** [comment]
var GUI_VERSION = "7555502"
var GUI_MONERO_VERSION = "049b7e9"

**Comment by Jaqueeee** [comment]
@voidzero can this be closed or are you still having issues?

**Comment by voidzero** [comment]
No issues anymore, I'll close it. Thanks.
