### ISSUE TITLE
New unconfirmed sent transactions listed at bottom of History

### ISSUE THREAD

**Issue by bigreddmachine** [monero-project/monero-core#367]
When a new transaction is sent from the wallet, before it is accepted into a block, it is listed at the bottom of the chart. Presumably this is because it is listed as in "block 0". Once confirmed, it moved up to the top, which makes sense. I think it should be at the top from the start, and say "block n/a" rather than "0".

**Comment by xmr-eric** [comment]
Great idea

**Comment by palexande** [comment]
Agree, new transactions need to be at the top whether sending or receiving.

**Comment by Jaqueeee** [comment]
fixed in #376 
unconfirmed shows as Block height: Pending

**Comment by bigreddmachine** [comment]
Good work!
