### ISSUE TITLE
Suggestion for block sync progress bar

### ISSUE THREAD

**Issue by voidzero** [monero-project/monero-core#387]
Right now, the progress bar is at almost 100% every time I start up the GUI because it's technically correct - right now I am at block 1217730 and need to sync to 1218152.

My idea is to make the progress bar instance specific. So when the GUI is started, the current block (1217730) could be 0% or 1%. That makes the progress bar a heck of a lot nicer.

**Comment by thoriumbr** [comment]
I think showing `Updating block 4 of 175` is more user friendly than `Updating block 1217730 of 1218152.`

**Comment by voidzero** [comment]
Ooh, yes, I like that one too.
