### ISSUE TITLE
[Feature Request] Start Daemon automatically if no .bitmonero dir found in $HOME.

### ISSUE THREAD

**Issue by dternyak** [monero-project/monero-core#39]
Messing with CLI commands for most users is not user friendly.
Can we allow the daemon to be shipped with the GUI and optionally auto-started?

**Comment by dternyak** [comment]
Moving to mbg033, seems to be more active.

**Comment by Jaqueeee** [comment]
imo it makes sense to keep feature requests in main repo. 
To the issue. An option to start/stop daemon from GUI would definitely be good. Not sure if auto-start is a good option though. Also, daemon could be configured to use other dir than .bitmonero in $HOME. 

I'm suggesting the following scenario instead.
- Check if daemon is running with RPC call to configured daemon address.
- if not found, present option to start daemon from GUI or alternatively option to change daemon address. 

What's your thoughts on this?

**Comment by dternyak** [comment]
Okay, I'll reopen it!

I think your suggested scenario is perfect and adds a lot of value. Do you think this falls within scope of the initial release?

**Comment by dternyak** [comment]
@Jaqueeee I'm willing to put on a small bounty (lets say 15 XMR) on this feature if you feel its out of scope. Ideally, the GUI shouldn't have any requirement for running CLI commands, and I think this is a great step towards that.

**Comment by Jaqueeee** [comment]
@dternyak sorry, I missed your last comment. I agree that the GUI should be able to run by itself in the future. It will take some effort to make this work cross platform so on the initial beta release the user will have to start the daemon separately most likely. CLI skills isn't really needed. A click on the monerod binary will be enough afaik.

**Comment by dternyak** [comment]
@Jaqueeee Thanks for the discussion. I see your point about the cross-platform GUI adding some complexity to the build (I assume the daemon binary must be built for each platform as well).

I think this should be a high-priority feature after the beta.

**Comment by medusadigital** [comment]
i agree with your view @dternyak about the priorization of that feature. once we have a stable GUI and some community feedback regarding performance, this should be addressed. nevertheless, for the first public beta, its unfortunately out of scope. 

how does big brother bitcoin do it? they also have a daemon i assume.

**Comment by Jaqueeee** [comment]
Added in #217
Please close.

**Comment by dternyak** [comment]
nice work @Jaqueeee  :)
