### ISSUE TITLE
Unlocked balance wait time

### ISSUE THREAD

**Issue by xmr-eric** [monero-project/monero-core#406]
I noticed how this awesome estimated wait time has been added to the GUI. So if there's 1/10 confirmations, and we have a 2 minute block time, then there are an estimated eighteen minutes remaining until my funds unlock "(~18 minutes)".

The problem is it says "~20 minutes" if it hasn't been mined yet, and there is a lot of congestion on the blockchain mempool at the moment.

What about having it say "> 20 minutes" when it hasn't been mined yet, and then once it has, going to ~18 minutes, ~16 minutes, etc. That way the GUI isn't saying people are going to get their funds in 20 minutes when in fact it could take an hour, as some transactions are currently taking.

**Comment by Jaqueeee** [comment]
You closed this? Can't recall it's implemented yet.

**Comment by xmr-eric** [comment]
@Jaqueeee I thought more about it, and realized that "> 20 minutes" sounds a bit dramatic. People could look at ">20 minutes" and think, "Oh man, how long is this going to take?!?" when in fact it'll probably take ~20 minutes.

Perhaps instead we could have the "~20 minutes" time be "waiting for mined block". And then once the block is mined, it clicks to ~18, ~16 etc. I'll repoen this task.
