### ISSUE TITLE
Advanced Tab Hotkey Broken

### ISSUE THREAD

**Issue by livinginformation** [monero-project/monero-core#415]
Pressing ctrl+A to access the Advanced tab does not work. Additionally, Hotkeys for Send, Receive, History, and Settings the hotkeys work properly, but make an error sound.

**Comment by unknownids** [comment]
can confirm happening on my computer. windows 10 64bit.

**Comment by Jaqueeee** [comment]
advanced hotkey fixed in #417, but i can't reproduce the error sound issue. Maybe that's windows only. Had to use "D" for advanced because ctrl+A is reserved for select all.

**Comment by livinginformation** [comment]
Error sound issue is on OSX, not Windows.

**Comment by Jaqueeee** [comment]
Weird. I'm also on OSX. Does it happen with both cmd and ctrl? Which osx version are you on?

**Comment by livinginformation** [comment]
10.10.1 Yosemite. It does happen with ctrl, and with cmd it happens only on the button presses where the keys aren't system hooks (command+H, command+A)
