### ISSUE TITLE
Serialization.portability_wallet problem

### ISSUE THREAD

**Issue by oPensyLar** [monero-project/monero-core#422]
Hi, 

I try to build from [AUR (ArchLinux) package](https://aur.archlinux.org/packages/monero-core-git) and I can not, the error message ...

[  FAILED  ] 4 tests, listed below:
[  FAILED  ] Serialization.portability_wallet
[  FAILED  ] Serialization.portability_outputs
[  FAILED  ] Serialization.portability_unsigned_tx
[  FAILED  ] Serialization.portability_signed_tx

This error occurs  building libwallet release (./build.sh)

Any ideas?

**Comment by moneromooo-monero** [comment]
This is a monero thing, not a GUI thing.
Does your monero tree have commit b3ca0c62 ? If not, that's likely the reason. If yes, please report this on https://github.com/monero-project/monero instead.

**Comment by xmr-eric** [comment]
Is this still an issue? Or can this thread be closed?
