### ISSUE TITLE
Change default log level to avoid exposing public address and txids

### ISSUE THREAD

**Issue by monerohow** [monero-project/monero-core#436]
Request: change default log level for CLI wallet so that no logs are written unless otherwise specified.

Some users don't have encrypted file storage (either because they have unencrypted hard drives, or use unencrypted online backup, or keep their files on company/university storage which other people can inspect, or keep their wallet on an unencrypted flash drive).

For these people, it'd be useful if the CLI wallet did not log to disk by default, so that they can rely completely on the encryption provided by the wallet password. Otherwise, their public address and txids are exposed in the log file if anyone gets access to the location of their wallet.

**Comment by moneromooo-monero** [comment]
Can you refile this on https://github.com/monero-project/monero/issues/ please ?

**Comment by monerohow** [comment]
Done
