### ISSUE TITLE
set the blockchain dir during startup and a convenient way after as well.

### ISSUE THREAD

**Issue by madLyfe** [monero-project/monero-core#448]
would be nice to have the ability at install for the gui to ask where to install the large blockchain rather than a default dir. dealing with flags is not very user friendly. this would also need to be thought of for when someone wants to move it at a later date as well w/o having to use flags. maybe a blockchain dir field in the main settings with a button to 'change dir'(it was already set at install, in the case of the feature above) and it would move it for you wherever you like with a progress bar since its 10gb.

i am new to all of this, and i take it the gui is supposed to be entry level friendly. these would be good improvements.

**Comment by Jaqueeee** [comment]
Added blockchain folder selection to settings page in #709. Not added to wizard yet.

**Comment by dEBRUYNE-1** [comment]
+resolved
