### ISSUE TITLE
Issues with send confirmation popup

### ISSUE THREAD

**Issue by medusadigital** [monero-project/monero-core#457]
![confirmation](https://cloud.githubusercontent.com/assets/17108301/22625152/7dd82a2c-eb8e-11e6-8992-c6e0f126c26f.png)

- ringsize is wrong (41 but should be 5)
- amount is 0.0000000000

**Comment by xmr-eric** [comment]
This has been fixed

**Comment by Jaqueeee** [comment]
@medusadigital close plz

**Comment by medusadigital** [comment]
fixed, closed
