### ISSUE TITLE
"Unlocked balance ~20 minutes" message even though there is no incoming tx

### ISSUE THREAD

**Issue by xmr-eric** [monero-project/monero-core#462]
Shouldn't the "unlocked balance" timer only be working if there are incoming/outgoing tx that haven't confirmed? Right now I have a testwallet that has no incoming/outgoing tx and yet it still shows this message.

![tx](https://cloud.githubusercontent.com/assets/21302237/22628385/1c60c8ae-eba1-11e6-8f22-f3837ffd667b.png)

**Comment by xmr-eric** [comment]
This message went away. I think I figured out where it came from.

Before I opened the GUI, I had just sent a transaction from the CLI. Like, I closed the CLI about 2 seconds after the payment ID appeared on my screen, and immediately opened the GUI. So for some reason the GUI had picked up the CLI transaction that had just been sent?

**Comment by Jaqueeee** [comment]
Yes, that would make sense if you opened the same wallet with GUI. GUI scans mempool continuously.

**Comment by xmr-eric** [comment]
There's what's weird. I didn't open the same wallet. It was a GUI test wallet unrelated to the CLI tx I had just sent

**Comment by Jaqueeee** [comment]
That's really weird. Let me know if you can reproduce it.

**Comment by xmr-eric** [comment]
I'm just going to close this. I'll reopen it if the issue pops up again.
