### ISSUE TITLE
history tab in gui does not autmatically refresh date/transactions

### ISSUE THREAD

**Issue by TheSwampThing** [monero-project/monero-core#467]
noticed some weird behavior in the GUI wallet

2 days ago i synced and left my wallet open since.
1 day ago the pool send me some XMR. it showed up in the balance indicator, but the transaction did not show in the 'history' tab. Only after close/restart gui it did appear. also, the filter date showed the date from when i opened the wallet, not today's date.
Apparently this page does not dynamically update both date and transactions.
gui version: 13253c3
embedded monero version dd580d7

**Comment by Jaqueeee** [comment]
@TheSwampThing first issue is fixed in #541.
