### ISSUE TITLE
Build: cannot find -lepee

### ISSUE THREAD

**Issue by voidzero** [monero-project/monero-core#470]
Trying to build monero-core on Linux 64bit (Gentoo) gives me this message.

So I tried to issue this command by hand:
`make -C monero/build/release/contrib/epee all install`
This does create libepee.a in monero-core/monero/lib/libepee.a. But when I follow it up with build.sh, the message is "cannot find -lepee" and when I check the directory monero/lib again, the file libepee.a is indeed gone.

So then I figured, let's prevent deletion and did 'chattr +i monero/lib/libepee.a'. Ran build again, and here's where it seems to happen:

<pre>
cleaning up existing monero build dir, libs and includes
rm: cannot remove ‘/mnt/coindb/src/monero-core/monero/lib/libepee.a’: Operation not permitted
</pre>

It still doesn't build - but that's now because of a different reason, lots of undefined references to cryptonote::foo.

**Comment by thoriumbr** [comment]
Edit `monero-wallet-gui.pro` and change this:

`-lepee \`
with
`$$WALLET_ROOT/build/release/contrib/epee/src/libepee.a \`

**Comment by voidzero** [comment]
Thanks for your comment. Yeah I did try that but essentially it's doing the same thing though because that path is already specified with -L.

But the problem is that libepee.a file disappears like I said.

The chattr +i is a working workaround but certainly not clean. I can't figure out where it is removed. It seems that get_libwallet_api.sh deletes stuff as part of "cleaning up existing monero build dir, libs and includes" but even if I comment it out it is deleted by something else. So the problem is not that libepee cannot be found - the problem is that libepee.a is unjustly deleted.

**Comment by voidzero** [comment]
Oh, and, after get_libwallet_api.sh I do have to run that make command by hand.

<pre>
make -C monero/build/release/contrib/epee all install
</pre>

**Comment by Jaqueeee** [comment]
This is fixed in #466 
Merge that PR and you should be ok. 
ping @fluffypony

**Comment by voidzero** [comment]
This is fixed indeed. Closing. Thank you!
