### ISSUE TITLE
"QtMultimedia not found" while it is installed

### ISSUE THREAD

**Issue by voidzero** [monero-project/monero-core#474]
I had to revert commit 93d2eb5e1a0 because, even though I got monero-core to compile (after jumping through some hoops related to my other issue re libepee), when I start it I get the message that QtMultimedia can't be found, while it is installed. Version 5.6.2 on Linux x64 (Funtoo, a Gentoo derivative).

I don't exactly know why I'm being told that QtMultimedia can't be found - somewhere I read that it might have to do with an optional dependency on gstreamer 0.10. I don't have that installed, because it's too old and pulls in a number of other dependencies I'd rather not use.

After reverting this commit, I can run monero-core succesfully again.

**Comment by moneromooo-monero** [comment]
Did you run qmake again ? Do you have an older version of qtmultimedia ?

**Comment by voidzero** [comment]
qmake is being executed from build.sh - QtMultimedia as stated is version 5.6.2..

**Comment by glv2** [comment]
Have you checked that *qtmultimedia* is compiled with the *qml* USE flag activated?

Also on my Gentoo system, I must compile using the command ```QT_SELECT=5 ./build.sh```. If I don't indicate the Qt version to use explicitly, it tries to use the Qt4 version of binaries and libraries.

**Comment by voidzero** [comment]
@glv2 it seems that I didn't enable the qml USE flag. Thanks for the tip. Regarding the QT_SELECT env var, I didn't know about that. I always just changed the qmake line to point to `/usr/lib/qt5/bin/qmake`. I'll try that suggestion too and update this issue again in a bit. Much thanks. :+1:

**Comment by voidzero** [comment]
Ok. Cool. This fixed it.

@moneromooo-monero could you add a comment into the README about these two things... Gentoo users need to enable the "qml" USE flag, and need to run `QT_SELECT=5 ./build.sh` or something similar?

Which reminds me.. since my shell is zsh and the script doesn't play nice with zsh, what I run is actually `env QT_SELECT=5 SHELL=/bin/bash ./build.sh` -- because even though build.sh contains a hashbang pointing to /bin/bash, it also uses $SHELL which is the problematic part because this var is not changed upon invocation. Ideally the hashbang would contain `#!/usr/bin/env bash` and instead of `$SHELL`, simply `bash` should be used.

**Comment by moneromooo-monero** [comment]
It'd be best if you  (or someone with Gentoo) did it, since I might write something slightly wrong since I don't use it.

**Comment by xmr-eric** [comment]
@voidzero Can this issue be closed?

**Comment by voidzero** [comment]
Busy as a bee and forgot all about adding those comments to the README. Sorry about that - @glv2 much thanks for adding #632. Means this one can be closed :+1:
