### ISSUE TITLE
Bottom left Progress Bar takes too long to initially display

### ISSUE THREAD

**Issue by medusadigital** [monero-project/monero-core#475]
Bottom left Progress Bar takes too long to initially display. while the "Connected" indicator changes state quickly, the Progress Bar takes up to half a minute until appearing for the first time.

**Comment by Jaqueeee** [comment]
Fixed in #489

**Comment by Jaqueeee** [comment]
can be closed?

**Comment by medusadigital** [comment]
Sorry @Jaqueeee for delay.

yes, closed
