### ISSUE TITLE
Issues experienced building in Subgraph OS (based on Debian stretch) + fixes

### ISSUE THREAD

**Issue by dma** [monero-project/monero-core#482]
We're looking at packaging the Monero GUI wallet and monerod for [Subgraph OS](https://subgraph.com). As a first step, I've written a guide to building and running them in SGOS:

https://subgraph.com/sgos/documentation/monero/

I'd appreciate feedback on this guide!

During my experience I encountered a couple of issues that are documented in the guide along with workarounds. Here is the issue filing for both of them if you want to fix them here:

1. The '&' character in this [line](https://github.com/monero-project/monero-core/blob/master/translations/monero-core_de.ts#L500) produces a parsing failure during the localization step of the build, causing the build to fail. It's here;

https://github.com/monero-project/monero-core/blob/master/translations/monero-core_de.ts#L500

2. Building in Subgraph OS requires -ldl to be included in the list of libraries when monero-wallet-gui is linked. It's not there by default, resulting in an unresolved symbol from glibc and build failure. I added it to this section here (-ldl at the bottom of the list), and then the build completed successfully and produced a usable executable:

https://github.com/monero-project/monero-core/blob/master/monero-wallet-gui.pro#L90

Thanks.

**Comment by danrmiller** [comment]
Cool, I'll give your guide a try. The two issues you mention are fixed in Pull Requests #477 and #478

**Comment by dma** [comment]
Didn't see those, should have checked. Thanks!
