### ISSUE TITLE
Run daemon as a windows service so the user is always synchronized with the network

### ISSUE THREAD

**Issue by Gingeropolous** [monero-project/monero-core#484]
Create an option to run the daemon as a service. This will allow the user relatively instant access to their Monero, wherein they will only have to wait for the wallet to synchronize.

**Comment by Jaqueeee** [comment]
can this be closed?

**Comment by antanst** [comment]
In my opinion if, after closing a window, something continues to run in the background, there should be a clear indication of doing so:

- On Windows, a system tray icon.
- On MacOS, a dock icon.
- On Linux (Gnome), a panel icon.

Having something (especially battery intensive like the Monero daemon) running in the background without clear indication of doing so will alienate users.

**Comment by medusadigital** [comment]
Hi @antanst , i openend a new issue regarding your feature request so it wont get lost. 

i hope thats fine. 

thanks for your suggestion

**Comment by dEBRUYNE-1** [comment]
+duplicate
