### ISSUE TITLE
Feature idea: simple point-of-sale system (receive transaction screen)

### ISSUE THREAD

**Issue by Gingeropolous** [monero-project/monero-core#5]
User #1 enters payment amount, hits "ok". QR code pops up, user#1 shows screen to user #2, user#2 scans code and sends payment. GUI then monitors mempool to see transaction enter mempool, reports "transaction received".

**Comment by ChristopherKing42** [comment]
Wouldn't it be "transaction pending" (since they can't spend it yet).

**Comment by Jaqueeee** [comment]
Added in #224 
Please close.

**Comment by dEBRUYNE-1** [comment]
+resolved
