### ISSUE TITLE
Solo mining not working

### ISSUE THREAD

**Issue by xmr-eric** [monero-project/monero-core#501]
Shows 0 h/s. Daemon viewer shows it is trying to "smart mine". Probably related to: https://github.com/monero-project/monero/issues/1810

Edit: I'm on OSX 10.12.3

**Comment by xmr-eric** [comment]
Strange. I stopped the daemon, changed the log level, restarted the daemon, and restarted the miner. This time it didn't smart mine, but it mined like normal, and I got 35 h/s. So perhaps smart mining is the only problem, though I don't understand why smart mining would begin when the daemon auto-starts vs. normal mining is enabled when I start the daemon manually.

**Comment by moneromooo-monero** [comment]
Probably because the GUI does not set the new smart mining options when calling the RPC, so they get set to random values, which the daemon reads and acts upon. There might be a number of RPCs with added fields which might need filling...

**Comment by xmr-eric** [comment]
@Jaqueeee Perhaps we can just forbid the GUI from smart mining, and this issue will be solved?

**Comment by Jaqueeee** [comment]
@xmr-eric @medusadigital Mining works for me with #1827

**Comment by xmr-eric** [comment]
@Jaqueeee Added #1827 and it works now
