### ISSUE TITLE
Integrated address: not working for size=64

### ISSUE THREAD

**Issue by voidzero** [monero-project/monero-core#522]
The Payment ID field says "16 or 64 hexadecimal characters", but when I create a random hash using `openssl rand -hex 32` and paste it, the Integrated Address field says "Invalid payment ID". It only works for 16 chars.

As an aside - the integrated field has no max length atm. Probably doesn't matter much but hey, since we're squashing bugs anyway, can't hurt to add it.

**Comment by Jaqueeee** [comment]
@voidzero integrated addresses only works with short payment id. Updated the description in #530

**Comment by voidzero** [comment]
Ahh. Perfect. Thank you. Guess this can be closed then.
