### ISSUE TITLE
Stuck at "Creating Transaction"

### ISSUE THREAD

**Issue by dternyak** [monero-project/monero-core#553]
Using a remote node. Not sure how to provide additional debug info. 

Using master 897bc582f042cdcecbaf8048bd9ab73f3f9b302b

Edit: Eventually timed out (5 mins or so, but crashed once before): 

```Can't create transaction: no connection to daemon. Please make sure daemon is running.```. 

I was able to sync with the same remote node, so I feel like there still might have been something client side that caused this. 

Somone else testing sending a transaction and confirming it does indeed work should be enough to close this issue, as remote nodes should not be relied upon.

**Comment by Jaqueeee** [comment]
Can you try with a different remote node? Any of these for example: node.moneroworld.com node.suppotxmr.com node.xmrbackb.one

**Comment by dternyak** [comment]
I tried with local daemon and it seemed to work, failed with both of those remote nodes. In one case it failed because the GUI crashed, in the other case it failed with `Can't create transaction: no connection to daemon. Please make sure daemon is running..`

**Comment by Jaqueeee** [comment]
Sounds like a timeout issue indeed. Will try to reproduce, thanks.
