### ISSUE TITLE
Daemon Log shows different block height than GUI

### ISSUE THREAD

**Issue by dternyak** [monero-project/monero-core#554]
<img width="298" alt="screen shot 2017-03-11 at 6 56 23 pm" src="https://cloud.githubusercontent.com/assets/7861465/23828107/84d66956-068c-11e7-9908-6ee4a831d4d3.png">

Using 897bc58

**Comment by dternyak** [comment]
A complete reboot did end up fixing this.

**Comment by Jaqueeee** [comment]
the target height used to count the remaining blocks is cached for 30 seconds. Did you wait longer than that?

**Comment by dternyak** [comment]
Yes, much longer than 30 seconds. The GUI was behaving strangely at the time, this coincided with the transaction error issue I posted. 

A reboot fixed this as well, so I'm inclined to believe it was some temporary funkyness on both sides. Going to close, but at least now you're aware there might be something going on.

**Comment by Jaqueeee** [comment]
ok. thanks. Will do another smoke test after point release.

**Comment by Jaqueeee** [comment]
@medusadigital pointed out that there's nothing wrong in that screenshot. Subtracting the numbers in the popup gives 961264 remaining blocks. More or less the same as shown in bottom left.

**Comment by dternyak** [comment]
Shoot, i was confused and thought it was the total # left still.
