### ISSUE TITLE
Build Fails: undefined reference to `boost::re_detail_106100

### ISSUE THREAD

**Issue by hamiltino** [monero-project/monero-core#57]
Hi,
I can't get monero core built on my system (debian sid) i get the following error on make:

```
` undefined reference to `boost::re_detail_106100::cpp_regex_traits_implementation<char>::transform_primary(char const*, char const*) const'
<artificial>:(.text+0x368d): undefined reference to `boost::re_detail_106100::cpp_regex_traits_implementation<char>::transform(char const*, char const*) const'
collect2: error: ld returned 1 exit status
Makefile:187: recipe for target 'release/bin/monero-core' failed
make: *** [release/bin/monero-core] Error 1
```

`

What needs to be done to get it working? I'm using libboost-all-dev (1.61.0.2) libboost-regex-dev (1.61.0.2)

**Comment by medusadigital** [comment]
is this still an issue? did you try libboost1.58 ?

**Comment by maitscha** [comment]
On OSX, I had a similar error with `boost` 1.62. I downgraded to 1.59, and now it works. See #101. I don't know if this is the same problem.

**Comment by fluffypony** [comment]
Closing as fixed
