### ISSUE TITLE
get_libwallet_api.sh static build flags

### ISSUE THREAD

**Issue by peronero** [monero-project/monero-core#58]
openSUSE doesn't ship static versions of libraries causing this script to fail due to it requiring static versions of libboost components. This might be the case with Arch as well.

Stripping out 'STATIC=ON -D' from the script successfully compiles a working monero-core build in Tumbleweed - albeit not yet tested with monerod and the blockchain. 

Are the static build flags actually necessary?

**Comment by dternyak** [comment]
This happens on OSX as well based on some user reports (not mine).

**Comment by anonimal** [comment]
On Arch (or with the [AUR package](https://aur.archlinux.org/packages/monero/)) I've never had this problem but I cannot confirm with a recent build because of #51.

**Comment by mbg033** [comment]
Static build is required for Windows at least (as it should work outside of msys2 environment and normally Windows PC doesn't have any boost and other dependencies installed).

I'll try without static on Linux, but normally it should be something like ```libmonero-dev``` (or ```libwallet-dev```) package which installs libwallet_api, appropriate headers + all dependencies, so building GUI doesn't involve building libwallet (monero).

Actually at the beginning I wanted to have it as "one big package containing all dependencies and installing to the separate directory into filesystem, like /opt", but yes, makes sense to use packages infrastructure on Linux.

**Comment by fluffypony** [comment]
Closing as fixed

**Comment by peronero** [comment]
This doesn't look fixed to me - I think I still see the offending flag in the bash script but now also get boost errors compiling monerod so cannot confirm.

**Comment by fluffypony** [comment]
Reopened by request
