### ISSUE TITLE
History shows different Amount before vs. after tx is mined

### ISSUE THREAD

**Issue by xmr-eric** [monero-project/monero-core#580]
Before being mined (amount includes fee)

![premine](https://cloud.githubusercontent.com/assets/21302237/24085652/0861ee54-0cd6-11e7-8c71-5442b25e6a7e.png)

After being mined (amount does not include fee)

![postmine](https://cloud.githubusercontent.com/assets/21302237/24085654/0e6581b2-0cd6-11e7-9d49-6e867d0c1094.png)

**Comment by dEBRUYNE-1** [comment]
+duplicate
