### ISSUE TITLE
Ouputs found by view-wallet but not by spending/regular wallet

### ISSUE THREAD

**Issue by dternyak** [monero-project/monero-core#588]
I have 2 transactions (outputs, not inputs, as I realize view wallet is not able to properly track inputs/spends) that the view wallet finds, but the spend wallet does not.

Neither of them use payment ids. 

I can provide more information directly as this seems to be a high-priority issue.

**Comment by Jaqueeee** [comment]
Is the spend wallet a cold wallet or is it connected to a node?
Have you tried rescanning the wallet cache? I would suggest renaming the cache and not delete it if you want to keep the tx keys.

**Comment by dternyak** [comment]
@Jaqueeee The spend wallet is connected to a local node, as is the view wallet.

I'll try re-creating the spend via mnemonic, that should work the same as renaming the cache afaik.

**Comment by Jaqueeee** [comment]
@dternyak yeah, it should do the same. But it will take longer time if you don't supply a restore height. Could you describe the workflow prior to this happened? You created a tx in view wallet and signed it in spend wallet, and then submited from view wallet? And now the transaction doesnt show up in the spend wallet?

**Comment by dternyak** [comment]
@Jaqueeee Unfortunately I only noticed the discrepancy between the view-wallet and spend wallet after a few weeks, so I can't remember exactly what I did on the day that they got out of sync. 

I *think* I had the view-wallet up and running when I sent the Monero, while connected to a remote node. 

At some later point, I switched to the spend wallet, and then a few weeks later I noticed that the amounts were off after I switched to a local node for both wallets. 

Not sure what else I can offer. I'll let you know what happens when I restore from mnemonic (in the process now).

**Comment by dternyak** [comment]
@Jaqueeee Mnemonic restore shows the same balance as spend, cannot find transactions that view does :/

Do you have other suggestions? Its a non-trivial amount of monero between those 2 transactions, so I really would prefer not to lose access to them.

**Comment by dternyak** [comment]
Sorry for spamming, but I just had another thought:

Is it possible for the GUI (spend) wallet to not be able to know all of the spends it made in the past?

I understand the view wallet could have a higher balance because it is not able to know all of the spends you made, but the spends the transaction history is showing does not match up with the difference between view and spend wallet.

E.g. I have 2 spends that the transaction history shows, totaling ~1 monero. However, the difference in the balance is 5 Monero (not exact values, but you get the idea.)

I definitely feel like the view-wallet has the correct balance (minus the 1 monero is not able to track that I know I did send), but maybe I am wrong and the GUI spend wallet simply isn't picking up a spend I made in the past that I forgot about.

**Comment by dternyak** [comment]
@Jaqueeee Final post:

I don't think theres a bug at all, just some confusing UX inherit due to the anon.

If my understanding of monero internals is correct, than an input to a new transaction will also have an input back to yourself if the input is smaller than the output (after the miner fee).

The view-only wallet is showing a transaction that I made that was a net-negative as a positive, e.g. sending 1 monero in the spend is actually receiving 20 in the view wallet.

I havne't been keeping track of my transactions outside of the wallet, so I can't say which (view/spend) is closer to reality.

Going to close, but we should note that this *will* be confusing to new users
