### ISSUE TITLE
Default new wallet directory path on Linux

### ISSUE THREAD

**Issue by peronero** [monero-project/monero-core#59]
Currently, for Linux, the default new wallet directory is set to 'homedir/Monero Accounts', which is not ideal for many reasons - chiefly that it pollutes the user's home directory, that there is a space in the name, and perhaps even that it unnecessarily exposes sensitive files which would not be regularly used by the same typical novice user that also wouldn't choose a path other than the one set as default.

Suggest setting the default directory for new wallets to '$monerodir/wallet' where $monerodir is currently .bitmonero as first option, or where the GUI binary is located as a second option.

Further suggest looping into a greater discussion about the organization of .bitmonero, which is understood to be in the process of being renamed to .monero, particularly with regard to compartmentalizing/future-proofing the directory structure - currently it is devoted to containing blockchain-related files only, which could be moved to '.monero/blockchain' allowing for the wallets directory to neatly coexist, and also for a 'testnet' directory and whatever other needs arise down the road.

Unsure as to what the current or optimal behaviors are on other platforms but perhaps they should be reviewed as well.

Also, the default directory 'Monero Accounts'  seems to be created when monero-core is initialized and is not removed if a different location is chosen.

**Comment by peronero** [comment]
Paragraph appended about non-removal of 'Monero Accounts' directory.

**Comment by Jaqueeee** [comment]
changed default location to $HOME/Monero/wallets and removed auto creation in https://github.com/monero-project/monero-core/pull/93
Each wallet will get an own subdir as before.

**Comment by medusadigital** [comment]
can be closed

**Comment by fluffypony** [comment]
Closing as fixed
