### ISSUE TITLE
.config directory name on Linux

### ISSUE THREAD

**Issue by peronero** [monero-project/monero-core#60]
Currently monero-core creates a 'The Monero Project' directory in .config to store .conf files - ideally this directory should not have spaces, perhaps something as simple as 'monero' is the best solution.

**Comment by mbg033** [comment]
Reason of this is the  [`Settings`](http://doc.qt.io/qt-5/qml-qt-labs-settings-settings.html) QML type that uses [`QSettings`](http://doc.qt.io/qt-5/qsettings.html) internally and does't offer any public API to change location where the data actually stored. Even more, on different platforms it stored in different places.
What is the problem with spaces actually?

**Comment by mbg033** [comment]
But yes, if we really have a reasons to move settings file to the different location - it can be custom implementation

**Comment by medusadigital** [comment]
decision here: https://github.com/monero-project/monero-core/pull/96

can be closed.

**Comment by peronero** [comment]
That cannot be an accurate assessment of the situation. 

There are no other Linux apps on my system using either spaces or capitals in their .config names, nor are there any on most systems - certainly not using spaces. 

It must be against some standards and specs, and we would be just be creating more work down the road for any packagers wanting to include Monero in a distro's repositories, even more additional work devising a clunky contingency plan to deal with legacy directories if this is not addressed before it goes into the wild, and generally looking like noobs using a 'The Monero Project' directory to store configs _on Linux._

The Atom project has a lengthy discussion about this on their github: https://github.com/atom/atom/issues/8281

Further, the Qt5 spec does not seem to limit the .config directory name to the organization.

> AppConfigLocation	"~/.config/<APPNAME>", "/etc/xdg/<APPNAME>"

> In the table above, <APPNAME> is usually the organization name, the application name, or both, or a unique name generated at packaging. Similarly, <APPROOT> is the location where this application is installed (often a sandbox). <APPDIR> is the directory containing the application executable.

http://doc.qt.io/qt-5/qstandardpaths.html

**Comment by hyc** [comment]
Fwiw, spaces in directory names are a horrible idea and generally NOT done on POSIX systems. I vote to change it to just "monero" too.

**Comment by peronero** [comment]
Fixed by #267.
