### ISSUE TITLE
Rename new wallet text field doesn't behave as expected

### ISSUE THREAD

**Issue by peronero** [monero-project/monero-core#61]
The rename wallet text field in the "wallet set-up wizard" doesn't behave as a user would expect such a text field to behave:
1. Characters in that field should be selectable
2. Right-mouse-click menu doesn't work (GNOME)
3. Perhaps the pre-populated text (currently 'My account name') should disappear when the field is clicked, but not sure about this

**Comment by M5M400** [comment]
same applies to the "auto donations percentage" field in the setup wizard

**Comment by Jaqueeee** [comment]
1. Fixed

**Comment by peronero** [comment]
Fixed.
