### ISSUE TITLE
monerod.exe causing high hard pagefaults

### ISSUE THREAD

**Issue by exemar** [monero-project/monero-core#614]
Ran LatencyMon with the monero daemon running form the beta gui client and noticed very high numbers of hard pagefaults from the monerod.exe process. I've attached a screenshot of the results from latencymon. If there's any other information I can provide to help identifying this issue please just let me know and I will do so. First time posting here (was redirected from reddit) so not really sure what information I should be providing. 
![monerohp](https://cloud.githubusercontent.com/assets/26716564/24361566/2207d60c-1302-11e7-9389-b09e82b6cfee.png)

**Comment by Jaqueeee** [comment]
@exemar Thanks. monerod.exe isn't related to this repo (GUI). Could you please add this to https://github.com/monero-project/monero/issues instead?

**Comment by Jaqueeee** [comment]
@exemar and please also provide some more info about your system. 
From #monero-dev:
<+hyc> how much memory involved?
19:32 total system RAM, total free, process size.
<+hyc> also, all LMDB reads are page faults.
19:33 that's how memory mapped files work...

**Comment by exemar** [comment]
@Jaqueeee ok adding it there instead. will add additional system info. Sorry not too knowledgeable about all this stuff just thought I might have spotted a bug and wanted to report it! are you saying the pagefaults are normal therefore and not a concern?

**Comment by medusadigital** [comment]
Pagefaults in latencyMon means the application expected something in Ram, but needs to go to look on disk insstead. If your music apllication does this, its bad (thats why latencymon tracks it). With monerod.exe i would say this is expected behaviour

**Comment by exemar** [comment]
Thanks for the clarification.
