### ISSUE TITLE
WalletImpl::integratedAddress unexpectedly overriding payment id

### ISSUE THREAD

**Issue by moneromooo-monero** [monero-project/monero-core#64]
This is straddling monero and the GUI a bit, but it seems best here:

In std::string WalletImpl::integratedAddress(const std::string &payment_id) const
if payment_id can't be parsed, a random one is generated instead.
This seems wrong, and potentially dangerous. It should error out instead (ie, return empty string, or throw).

**Comment by moneromooo-monero** [comment]
https://github.com/monero-project/monero/pull/1228

**Comment by fluffypony** [comment]
Fixed
