### ISSUE TITLE
Launching Monero GUI on Linux and Wallet Hangs on Black Screen

### ISSUE THREAD

**Issue by guini-monero** [monero-project/monero-core#641]
So I am using Fedora 25, and when I run "./monero-wallet-gui," it does not respond and I'm left to force quit the process.

**Comment by peronero** [comment]
Have you tried running the bash script?

`./start_gui.sh`

**Comment by guini-monero** [comment]
Just did, and it did not seem to make a difference.

**Comment by guini-monero** [comment]
This is the "monero-wallet-gui.log":
```
2017-03-29 17:29:23.232	    7f1112673740	INFO 	global	contrib/epee/src/mlog.cpp:145	New log categories: *:WARNING,net:FATAL,net.p2p:FATAL,net.cn:FATAL,global:INFO,verify:FATAL,stacktrace:INFO
2017-03-29 17:29:24.147	    7f1112673740	INFO 	global	contrib/epee/src/mlog.cpp:153	New log categories: *:WARNING,net:FATAL,net.p2p:FATAL,net.cn:FATAL,global:INFO,verify:FATAL,stacktrace:INFO
```

**Comment by guini-monero** [comment]
This is also on the 64-bit version.

**Comment by swalecko** [comment]
Same here on Win10 64 bit, Intel Core i5-5200U CPU @ 2.20GHz , Intel HD Graphics 5500, Display solution 1920 x 1080 Full HD

**Comment by medusadigital** [comment]
hei @guini-monero , did you try this allready ? https://monero.stackexchange.com/questions/2928/how-to-change-the-monero-wallet-gui-rendering-mode-for-older-computers/2929#2929

**Comment by medusadigital** [comment]
set QMLSCENE_DEVICE=softwarecontext && ./monero-wallet-gui

**Comment by mariodian** [comment]
The same happens occasionally on MacBook Pro 2016 13" with the latest OSX Sierra 10.12.4. I have to quit the process and restart several times before it works normally.

**Comment by wostl** [comment]
Same here on Windows 8.1 and 10, 64 bit.

**Comment by mariodian** [comment]
After a bit of investigation I found that if I start monerod from the console first, wait ~10 seconds and then open the GUI, everything works normally.

**Comment by muusbolla** [comment]
On Win7 64bit I randomly had this problem. Starting monerod first did not work. Running with start-low-graphics-mode.bat did not work. As usual, rebooting the PC was the fix... typical Windows.

**Comment by medusadigital** [comment]
probably this was the issue: https://github.com/monero-project/monero-core/pull/777

i therefore consider this as +resolved until further notice
