### ISSUE TITLE
GUI has become unusable since last update. Everything too large

### ISSUE THREAD

**Issue by t4777sd** [monero-project/monero-core#660]
Since the last release the GUI has become unusable on ubuntu. Everything is enlarged such as the software becomes useless. The left hand menu gets cut off the screen due to the enlarged. Attached is a screenshot
![monero](https://cloud.githubusercontent.com/assets/2925965/24640523/ee53cb5a-18cd-11e7-8c5d-f3be18e686c5.png)

**Comment by medusadigital** [comment]
hi,

does this build solve the issue ? 

https://build.getmonero.org/downloads/monero-core-0508442-linux-amd64.tar.gz

**Comment by t4777sd** [comment]
Yes, that build resolves the issue. Is there any way to resolve the issue with the existing build (chanage config or something)?

**Comment by Jaqueeee** [comment]
Good to hear. Yes, you should be able to set the QT_SCALE_FACTOR environment variable. 
i.e to make it half the size:
`QT_SCALE_FACTOR=0.5 ./start-gui.sh`

Please let us know if this works for you.

**Comment by amiuhle** [comment]
Related: https://github.com/monero-project/monero-core/issues/343#issuecomment-285881929

Running the Beta 2 with a scale factor of 0.6 works best for me, @medusadigital's build is too small (tiny, as was Beta 1). Both solve the missing bullets when entering a password.

**Comment by medusadigital** [comment]
thanks a lot for your feedback guys !

**Comment by t4777sd** [comment]
The QT_SCALE_FACTOR made existing builds usable. However the build provided by medusadigital was the best looking

**Comment by Jaqueeee** [comment]
fixed in #647

**Comment by dEBRUYNE-1** [comment]
+resolved
