### ISSUE TITLE
[feature request] Rename this repo to monero-GUI

### ISSUE THREAD

**Issue by Jaqueeee** [monero-project/monero-core#663]
ping @fluffypony

**Comment by amiuhle** [comment]
Contrary to #654. I'm in favor of renaming the repository (or neither).

Also pinging @Gingeropolous.

Relevant Reddit posts:

* [Names, names and more names. : Monero](https://www.reddit.com/r/Monero/comments/62iscn/names_names_and_more_names/)
* [Results of the name survey : Monero](https://www.reddit.com/r/Monero/comments/62sdkm/results_of_the_name_survey/)
