### ISSUE TITLE
Issue Getting The Daemon To Start

### ISSUE THREAD

**Issue by Jayhorns** [monero-project/monero-core#664]
I have been asked to post this potential issue here. I am trying to use the Windows 64bit version of the GUI. The application appears to have synchronized successfully after about 8 hours, but I cannot get the daemon to start. I receive this message: "Daemon failed to start. Please check your wallet and daemon log for errors. You can also try to start monerod.exe manually." However, the log does not show any message or text at all. And despite the message, the network status still says Connected and monerod is running as a background process in the task manager.

The solution that seemed to work for another user did not work for me (rename the folder that contains the monero-wallet-gui Application to "MoneroGui2").

If I run the monerod application manually, eventually I get a message that says: "You are now synchronized with the network. You may now start monero-wallet-cli."

With all that said, am I synced with the network and able to send Monero to this wallet despite the error message with the daemon?

http://i.imgur.com/dPVB7l6.png

**Comment by TheRealMadmortigan** [comment]
I'm having the same issue.  The daemon does eventually start, but not until the initial connection times out.  I'm able to receive but sending has been "problematic" at best.

**Comment by Jaqueeee** [comment]
@Jayhorns Running the gui from C:\some folder\MoneroGui2 won't work either. So you need to ensure there are not spaces in the full path. 
Please also try this build https://build.getmonero.org/downloads/monero-core-5d45967-win64.zip
It's from https://github.com/monero-project/monero-core/pull/646

**Comment by Jayhorns** [comment]
@Jaqueeee I actually have the extraction on my D: drive (D:\My Name\Monero\MoneroGui2). So in this instance, can I run the GUI from the D: drive by making sure there are no spaces in the full file path? Or do I need to move it to the C: drive AND make sure there are no spaces in the full file path?

**Comment by Jaqueeee** [comment]
@Jayhorns It should work with D: drive also. As long as there are no spaces.

**Comment by Jayhorns** [comment]
Looks like I am synced, connected, and daemon running! Thank you.

**Comment by Jaqueeee** [comment]
Fixed in #646

**Comment by TheRealMadmortigan** [comment]
Nice work, gents!
