### ISSUE TITLE
Windows build - Cannot click Cancel or Okay in tx window if buttons fall below taskbar

### ISSUE THREAD

**Issue by HugTime** [monero-project/monero-core#665]
When sending a transaction, if the "Cancel" and "Ok" buttons fall below the taskbar they become unclickable.  The main GUI window can also not be moved at this point, so the only method I found to continue was to force-quit the GUI.

Version monero-gui-10.3.1-beta2 on Windows 10

**Comment by HugTime** [comment]
@Jaqueeee the popup confirmation dialogue opens up in the middle of the windowed GUI but the Cancel and Ok buttons may still fall below the Taskbar when the windowed GUI is low enough on the screen.  The windowed GUI cannot be moved at that point after the popup window has been opened and the buttons to close the popup are obscured, making the program inoperable.

**Comment by Jaqueeee** [comment]
OK. Now I understand. Maybe we could change the default position to center of screen instead of relative to the window.
