### ISSUE TITLE
payment page: Inform user why send button is disabled

### ISSUE THREAD

**Issue by Jaqueeee** [monero-project/monero-core#67]
Send button is disabled if address, amount or payment_id isn't valid. The user should be informed why it's disabled.

**Comment by moneromooo-monero** [comment]
I suggest making the input widget with the faulty input to have a light red background, I'm sure that's easy to do.

**Comment by moneromooo-monero** [comment]
https://github.com/monero-project/monero-core/pull/117

**Comment by dternyak** [comment]
@Jaqueeee This can be closed

**Comment by fluffypony** [comment]
Closing as fixed
