### ISSUE TITLE
Missing Fonts

### ISSUE THREAD

**Issue by medusadigital** [monero-project/monero-core#675]
On whonix x86, fonts are completely missing.

also some x64 linux distributions seem affected

**Comment by medusadigital** [comment]
https://www.reddit.com/r/Monero/comments/6316na/gui_no_text/

**Comment by Jaqueeee** [comment]
Related https://garlicgambit.wordpress.com/2017/04/16/monero-gui-blanked-out-text-issue-tails-2-11/

**Comment by Jaqueeee** [comment]
Made some changes to build env. This build works in Tails 2.12: https://build.getmonero.org/downloads/monero-core-af1edc0-linux-i686.tar.gz

Can @medusadigital test ^ on Whonix?

**Comment by dEBRUYNE-1** [comment]
+resolved
