### ISSUE TITLE
Wrong date in transaction history

### ISSUE THREAD

**Issue by MaxXor** [monero-project/monero-core#677]
There seems to be that all dates in the transaction history before 2016-09-21 (hardfork v3) are wrong. My other transactions after that date are shown correctly.

![transaction_history](https://cloud.githubusercontent.com/assets/7271470/25039497/1dfc799a-2104-11e7-87c3-974185b4496a.png)

**Comment by jonathancross** [comment]
Interesting that they are all the exact same date, yet very different block heights.

Can you please add details about your platform, Monero GUI version number, is this a binary release or built from source, etc.

Note: I am not seeing this behavior in the latest binary release v0.10.3.1 (GUI Beta 2) for Mac OSX.

**Comment by MaxXor** [comment]
Yes, indeed very strange. I'm using the binary release v0.10.3.1 (GUI Beta 2) on Windows 7 64bit.

**Comment by medusadigital** [comment]
i have seen this bug, but it was months ago before beta 1 release and never happened again.

is this wallet cache completely created with GUI beta 2 ?

**Comment by MaxXor** [comment]
The wallet was created with monero-cli 0.9 if I remember correctly and I've never used the GUI until now. Could I possibly fix it when I delete the cache and do a full re-scan of the wallet?

**Comment by MaxXor** [comment]
Restored the wallet from seed and did a full re-scan. Now it shows the correct dates for all my transactions, thanks @medusadigital.
