### ISSUE TITLE
Disable GUI until wallet is fully loaded

### ISSUE THREAD

**Issue by Jaqueeee** [monero-project/monero-core#68]
if I click on the receive tab instantly after opening a wallet this happens (se image). The buttons in left panel should be disabled until wallet is fully loaded. 
see: https://github.com/monero-project/monero-core/blob/master/main.qml#L403

![skarmavbild 2016-10-16 kl 17 42 11](https://cloud.githubusercontent.com/assets/5909557/19418619/ec922180-93c7-11e6-99d2-21ed5e29e6a6.png)

**Comment by Jaqueeee** [comment]
If i switch to another tab and then return to the receive page the addresses are there.

**Comment by medusadigital** [comment]
Disabling The Tab until the daemon is synced is probably not the best idea @Jaqueeee, since long term we still want the user to be able to generate addresses offline without being synced/having the chain

**Comment by taushet** [comment]
@medusadigital, we can have an offline mode in the future.

In the short term, this is needed, as otherwise people will lose their minds not understanding why things are not working.
