### ISSUE TITLE
error while downloading beta 2 in windows and linux

### ISSUE THREAD

**Issue by AgoraJacob** [monero-project/monero-core#687]
a friend and me both(im on linux mint btw gui does not work properly still for me but thats for me to figure out) and friend on windows 10 downloaded the 64 bit betas and we got half files. not the whole zip i reuploaded the 64 bit windows for him after i downloaded and checked the md5 checksum and it seemed to work. it might be a hosting error? not sure but wanted to report
oh yeah all hail monero!

**Comment by dEBRUYNE-1** [comment]
This is probably resolved by now.

+resolved
