### ISSUE TITLE
GUI 2beta on W7 64b claims double spend even after re-sync following a failed 'pending' tx

### ISSUE THREAD

**Issue by Bits-of-Wisdom** [monero-project/monero-core#691]
GUI 2beta on W7 64b claims double spend even after re-sync following a failed 'pending' tx

I have GUI2beta installed on W7 64b and I tried to create a transaction for xmr.to, which stayed on 'pending'. I followed the SE guide, flushed the tx pool in the deamon and re-scanned from scratch the wallet, so now it shows my old balance. HOWEVER: trying to send Monero now results in an Error message: " Couldn't send the money: transaction <TX ID> was rejected by daemon with status: Failed. Reason: double spend"
Which is by the way after daemon is flushed tx and .key file only left on the wallet so it did a full blockchain sync from scratch.
How to be able to spend from my balance now?

Thank you in advance!

**Comment by Jaqueeee** [comment]
There is a "rescan spent" button in GUI that should fix this.

**Comment by Jaqueeee** [comment]
@Bits-of-Wisdom did "rescan spent" help? Please close issue in that case.

**Comment by dEBRUYNE-1** [comment]
This is probably resolved by now.

+resolved
