### ISSUE TITLE
[Feature request] "Fix busted wallet" option

### ISSUE THREAD

**Issue by Gingeropolous** [monero-project/monero-core#700]
Some button that attempts to fix a wallet thats broken.

For instance, this seems like a good goto

"Removing the cache would result in losing the private tx keys (which are needed in case of disputes) and recipient addresses (which may come in handy from time to time). In this case it's better to first open monerod and type "flush_txpool". Subsequently, open monero-wallet-cli and type "rescan_spent". "

https://bitcointalk.org/index.php?topic=583449.msg18786307#msg18786307

**Comment by Jaqueeee** [comment]
"rescan spent" is already available. Moved button to settings page in #707 and renamed it to "Rescan wallet balance". Not adding "flush_txpool" for now since it's potentially dangerous for avg users. (the tx could still be mined and the user can end up with sending multiple times)
