### ISSUE TITLE
"Network status - Connected" message confusing

### ISSUE THREAD

**Issue by knaccc** [monero-project/monero-core#726]
When I launch the GUI wallet, it first says "Network status - Connected". This means that if my wallet is not synchronized with the daemon yet, I will not have any visual indication that I need to wait to see the most up-to-date balance figure for my wallet. Someone that thinks their balance should be higher will panic for the first minute wondering if something has gone wrong.

Then after about a minute, it says "Network status - Synchronizing". This is my first indication that my wallet might not be showing a balance that reflects the latest state of the blockchain.

After the synchronizing finishes, and my balance does reflect the latest state of the blockchain, it goes back to "Network status - Connected", which is a message indistinguishable from the situation where my wallet has yet to synchronize.

Hopefully it should be quite straightforward to quickly determine the block height that other nodes are seeing, and display a more informative message when a user starts the GUI.

**Comment by medusadigital** [comment]
very related: https://github.com/monero-project/monero-core/issues/766

basically a new introduced state will solve the issue. status will show something like "connecting..." as long as wallet is waiting to start synchronize. 

will close this in favour of the other ticket.

+duplicate
