### ISSUE TITLE
Can not compile in debug mode

### ISSUE THREAD

**Issue by MaxXor** [monero-project/monero-core#749]
Hello,
I'm trying to track down issue #524, but I'm stuck at trying to compile the project in debug mode. I get the following errors when I try to build with command `./build.sh debug`:
> /usr/bin/ld: cannot find -lwallet_merged
> /usr/bin/ld: cannot find -lepee
> /usr/bin/ld: cannot find -leasylogging

**Comment by Jaqueeee** [comment]
There's most likely a previous error in get_libwallet_api.sh where those libs are built. 
Try running that script explicitly before running build.sh and see if you get any errors. 
`./get_libwallet_api.sh debug`

**Comment by MaxXor** [comment]
I'm getting many errors like the one below when executing that script.
>CMake Error at external/easylogging++/CMakeLists.txt:53 (install):
>install TARGETS given no LIBRARY DESTINATION for shared library target
>"easylogging".

**Comment by Jaqueeee** [comment]
the one liner in #751 fixes the issue for me on osx. It makes the debug build static. You need to delete monero/build folder before trying again.

**Comment by MaxXor** [comment]
Thanks, that fixed it.
