### ISSUE TITLE
"The more that people mine"

### ISSUE THREAD

**Issue by romenoo** [monero-project/monero-core#756]
> The more that people mine, the harder it is for the network to be attacked

Shouldn't the wording be "The more people that mine" instead?

**Comment by jonathancross** [comment]
Hmmm... having a large set of miners makes the network more decentralized / difficult to attack, but it is not as important as the **_amount_** of mining (H/s) they are contributing.

For example: If many people are mining, but only for 10 minutes a day on an old computer, that will not help the network.

**Comment by xmr-eric** [comment]
I'm the person who wrote that description. The reason for the words is what Jonathan said, that the amount of mining (hashrate) is what protects the network, not the actual number of people.

**Comment by medusadigital** [comment]
+wontfix
