### ISSUE TITLE
Windows 64 issues GUI Beta 2  Black screen/crashing.

### ISSUE THREAD

**Issue by Throwaway674422** [monero-project/monero-core#761]
I am having an issue with the beta gui.  When trying to run the exe it just opens a black screen, hangs, then crashes. I have also tried to run the low-graphics batch file, with no luck. When I double click it, cmd window pops up, then closes immediately, that is it.

Running Windows 7 Ultimate
Intel I7 12gb

Log
https://paste.fedoraproject.org/paste/m7LZhp6te8ExH6WXO3mq6V5M1UNdIGYhyRLivL9gydE=

**Comment by muusbolla** [comment]
I had this issue today on Windows 7 64bit as well. The logfile didn't seem to show anything meaningful for me either. Restarting my PC fixed it... sigh, Windows.

**Comment by Throwaway674422** [comment]
I have restarted multiple times with no avail.

**Comment by eth125754** [comment]
I'm having a very similar issue. Exact same log.

The process monero-wallet-gui runs but no screen shows. 

Windows 10 64bit

**Comment by Jaqueeee** [comment]
@eth125754 Have you tried the low graphic bat file?

**Comment by eth125754** [comment]
Yeah, that starts a command line but nothing is displayed on it. It starts a process as well but nothing else happens as far as I can tell.

**Comment by medusadigital** [comment]
@eth125754  can you tell us what computer you have ?

**Comment by Pecral** [comment]
I've experienced the same problem as you and it was reproducable as soon as I've used Google's DNS servers (8.8.8.8 and 8.8.4.4) - The problem didn't occur while using my ISP's DNS server. Unfortunately your log-file isn't available anymore so I can't compare whether I had the same log-file, but you can increase your log-level to see where the process hangs.

**Comment by medusadigital** [comment]
thanks a lot @Pecral, your feedback helps a lot

**Comment by MaxXor** [comment]
@Pecral Never had issues with the Monero Wallet GUI on Windows 7 Enterprise 64 bit and I'm also using Google's DNS servers. 😕 Don't think it has anything to do with DNS.

**Comment by eth125754** [comment]
@medusadigital Sure, it's a Windows 10 Home edition 64 Bit. i5-6600K with 16GB RAM. The Moneorod runs fine, just not the gui exe. The text file reads out this:

2017-06-21 19:03:55.492	3732	INFO 	global	contrib/epee/src/mlog.cpp:145	New log categories: *:WARNING,net:FATAL,net.p2p:FATAL,net.cn:FATAL,global:INFO,verify:FATAL,stacktrace:INFO
