### ISSUE TITLE
A better `start-gui.sh` script

### ISSUE THREAD

**Issue by oerdnj** [monero-project/monero-core#765]
The start-gui.sh script has to be run from the "installation" directory now as it runs `./monero-wallet-gui`. The improved version can be called from elsewhere including linking it to `~/bin/monero-gui` (as an example).

I can find the script anywhere in the repository hence the issue and not PR.

```
#!/bin/bash
MONERO_HOME=$(dirname $(realpath ${0}))
export LD_LIBRARY_PATH=${MONERO_HOME}/libs
export QT_PLUGIN_PATH=${MONERO_HOME}/plugins
export QML2_IMPORT_PATH=${MONERO_HOME}/qml
exec ${MONERO_HOME}/monero-wallet-gui
```

**Comment by jonathancross** [comment]
Hi @oerdnj, the script is created here:
https://github.com/monero-project/monero-core/blob/master/linuxdeploy_helper.sh#L44

You can make your change there and submit as a Pull Request.

**Comment by medusadigital** [comment]
can this be considered as done?

looking good to me.

will close for now until further notice. please respond here or open a new ticket if there is still something that neeeds to be done.

+resolved
