### ISSUE TITLE
Sign/verify 'Signature' input box broken on latest build monero-core-osx-10.12

### ISSUE THREAD

**Issue by tficharmers** [monero-project/monero-core#767]
The attached screenshot shows the 'Signature' box for the Verify form to be broken/squashed. This was from build #778.

![screen shot 2017-06-15 at 11 49 13](https://user-images.githubusercontent.com/23356013/27178810-9fd3a23c-51c3-11e7-9169-54912c6bd13b.PNG)

**Comment by jonathancross** [comment]
This is on Linux, correct?
Is it always squashed or are there steps to reproduce?

**Comment by tficharmers** [comment]
Definitely macOS. I just went to the sign/verify tab and it was just like that. It was from build #778, not the official beta release. I got it from the [buildbot page](https://build.getmonero.org/builders/monero-core-osx-10.12). Can't test later builds yet as they have failed.

**Comment by jonathancross** [comment]
Thanks for confirming platform and build, I am also seeing this issue on OSX.
I haven't tested yet, but it appears this might be the culprit:
https://github.com/monero-project/monero-core/blob/master/pages/Sign.qml#L422

**Comment by Jaqueeee** [comment]
I'm also seeing it. i'll look into it soon^tm

**Comment by MaxXor** [comment]
This issue is platform-wide, not OSX specific. Fixed it in the referenced PR.
