### ISSUE TITLE
Running monero gui 2 on tails does not display text

### ISSUE THREAD

**Issue by KushGoyal** [monero-project/monero-core#768]
On running monero gui 2 on tails the text is not displayed. To correct this I included this line in the start-gui.sh file.

```bash
export QT_QPA_FONTDIR=/usr/share/fonts/truetype/unifont/
```

Perhaps a specific font file can be included in the distribution files.

Another issue is that the gui screens are not scrollable. On my tails os screen I was not able to access the advanced option buttons on the send transaction screen.

**Comment by jonathancross** [comment]
Hi @KushGoyal can you please test and review #769 ?

**Comment by KushGoyal** [comment]
@jonathancross sure. I will test this and reply back.

**Comment by Jaqueeee** [comment]
The Linux32 builds from buildbot has working fonts in tails and whonix. Without any system env variables. Problem was that fluffypony didn't have fontconfig installed when he built QT and gui beta 2.

**Comment by dontbuymonero** [comment]
Is Tails 3.0 being used? Was released 2 days ago I believe.

**Comment by Jaqueeee** [comment]
We have tested 64 bit Linux gui on tails 3 beta without any issues iirc.

**Comment by jonathancross** [comment]
> fluffypony didn't have fontconfig installed when he built QT and gui beta 

Thanks @Jaqueeee. Would it make sense to check for `fontconfig` in build.sh so builds don't have this issue in the future?

**Comment by Jaqueeee** [comment]
@jonathancross: no, the issue appears when you've built Qt from source without fontconfig installed. Which was the case on the linux32 build machine used by buildbot and fluffy.

**Comment by dEBRUYNE-1** [comment]
+resolved
