### ISSUE TITLE
pt-br translation

### ISSUE THREAD

**Issue by fabionitto** [monero-project/monero-core#772]
I noticed several unfinished translations in pt-br file such as:
```
<message>
         <location filename="../pages/Settings.qml" line="257"/>
         <source>Blockchain location</source>
         <translation type="unfinished"></translation>
</message>
```
None of the other languages has it translated yet too. Are they waiting something? Or can I work on these at pt-br translation?

**Comment by Jaqueeee** [comment]
That string was added recently so it hasn't been translated yet. Feel free to translate it.

**Comment by fabionitto** [comment]
Thank you. I did a PR. It was my first, so I hope I did nothing wrong.
