### ISSUE TITLE
'Limit' command in GUI wallet sets download and upload speed to zero instead of displaying current speeds. 

### ISSUE THREAD

**Issue by mLouMN** [monero-project/monero-core#805]
settings>show status>(enter 'limit')>press enter

**Comment by medusadigital** [comment]
what you mean by "displaying current speed" ? 

the "limit" command comes from monerod and is used to set daemon upload and download speed.

there is no command to see which speed currently set.

**Comment by Jaqueeee** [comment]
yes, if you enter "limit" alone in monerod it shows the current limit.
+bug

**Comment by mLouMN** [comment]
To clarify:

Enter 'limit' in monerod.exe

Now open the GUI wallet > status > 'limit'

Why do they do different things?

**Comment by medusadigital** [comment]
ah sorry i did not know about that feature, my mistake

**Comment by MaxXor** [comment]
This is actually a `monerod` bug. Fixed it in the PR referenced above.

**Comment by dEBRUYNE-1** [comment]
+resolved
