### ISSUE TITLE
Transaction History does not scale anymore beyong initial window size

### ISSUE THREAD

**Issue by medusadigital** [monero-project/monero-core#809]
Transaction History does not scale anymore beyond initial window size.

![historyscaling](https://user-images.githubusercontent.com/17108301/29044544-3b8095de-7bc0-11e7-83fc-ab6eeee1a7e7.jpg)

running https://build.getmonero.org/builders/monero-core-win64/builds/881

+bug

**Comment by danrmiller** [comment]
Label commands need to be in an issue comment and not in the issue body.

+bug
