### ISSUE TITLE
Mac GUI fully quits, instead of hides, when you press the top-right red X button.

### ISSUE THREAD

**Issue by dontbuymonero** [monero-project/monero-core#816]
For most mac apps, pressing the top-right red X button does not mean close, it means hide. In other words, the application continues to run, but its window does not appear on the dock. Then to have the window reopen on the desktop, you just need to click the app's icon on the dock (as opposed to an additional window for the current session). 

Currently the Mac GUI (a) automatically quits when clicking the red X, and (b) does not ask "are you sure you want to quit first, in other words, you have no choice.

As a mac user, I can tell you it is very annoying when apps behave this way, because we are so used to constantly clicking the red-X button to hide our apps, and because we do not like cluttered docs.

**Comment by Jaqueeee** [comment]
#216 
+duplicate
