### ISSUE TITLE
Problem building on Trisquel: "ISO C++ forbids declaration of ‘Q_ENUM’..."

### ISSUE THREAD

**Issue by Riiume** [monero-project/monero-core#819]
Hi all, after (seemingly) installing all the dependencies via apt-get, I get the following error when running ./build.sh:

`../src/libwalletqt/PendingTransaction.h:29:18: error: ISO C++ forbids declaration of ‘Q_ENUM’ with no type [-fpermissive]
     Q_ENUM(Status)`

My Linux distro information:
`Linux version 3.13.0-123-generic (pbuilder@devel.trisquel.info) (gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.3) ) #172+7.0trisquel2 SMP Thu Jun 29 20:03:33 UTC 2017
`

Here's the full output from ./build.sh
[BuildOutput.txt](https://github.com/monero-project/monero-core/files/1221415/BuildOutput.txt)

Here's a list of all libraries I have installed via apt-get:
[AptList.txt](https://github.com/monero-project/monero-core/files/1221416/AptList.txt)

In particular, have all of the QT5 packages installed, but it seems that in Trisquel the qml-module-* packages are named differently. Here are the qml related packages I have installed:

```
libqt5qml-graphicaleffects/belenos,now 5.2.1-1 amd64 [installed]
libqt5qml5/belenos-updates,now 5.2.1-3ubuntu15.1 amd64 [installed]
qtquick1-qml-plugins/belenos,now 5.2.1-1ubuntu1 amd64 [installed]
qtquick1-qmltooling-plugins/belenos,now 5.2.1-1ubuntu1 amd64 [installed]
```

**Comment by Riiume** [comment]
Ah, I overlooked this, but it looks like CMake couldn't find the correct version of Boost, would fixing Boost also fix the Q_Enum issue?
```
CMake Error at /usr/share/cmake-2.8/Modules/FindBoost.cmake:1131 (message):
  Unable to find the requested Boost libraries.

  Boost version: 1.54.0

  Boost include path: /usr/include

  Detected version of Boost is too old.  Requested version was 1.58 (or
  newer).
Call Stack (most recent call first):
  CMakeLists.txt:643 (find_package)


CMake Error at CMakeLists.txt:48 (message):
  Could not find Boost libraries, please make sure you have installed
  Boost or libboost-all-dev (1.58) or the equivalent
```

**Comment by Jaqueeee** [comment]
hi @Riiume 
Was the original issue solved by updating boost? If not, my suggestion is upgrading Qt. I think you'll need 5.5 at lowest. But I'd recommend 5.8.

**Comment by Riiume** [comment]
I couldn't install boost 1.58 via `apt-get` so i had to use `wget` to retrieve the source and then run `./bootstrap.sh`, etc.

But now it seems like cmake is looking up the wrong version of Boost (it's not realizing that I have just installed Boost 1.58). I'm trying to adjust the BOOST_ROOT, BOOST_INCLUDEDIR, and BOOST_LIBRARYDIR environment variables used by FindBoost.cmake  but that doesn't seem to be working.

What I know for certain is that 1.58's lib and include are `/usr/local/lib` and `/usr/local/include`, respectively.

**Comment by Riiume** [comment]
Looks like it's insisting on `Boost include path: /usr/include` even though I've done `export BOOST_INCLUDEDIR=/usr/local/include/boost` and `export BOOST_LIBRARYDIR=/usr/local/lib`.

Sorry, I'm a noob, LOL

**Comment by Riiume** [comment]
Aha! I think I've got it working-- had to delete the ~/monero-core directory, download a fresh copy, then run build.sh, and now it's detecting the new Boost settings!

**Comment by Riiume** [comment]
Gah, okay that resolved the Boost errors, but I'm still back to receiving the Qt errors: 
[BuildErrors.txt](https://github.com/monero-project/monero-core/files/1221801/BuildErrors.txt)

**Comment by Jaqueeee** [comment]
Ok. Qt5 could mean anything between 5.0 - 5.9. `qmake -v` should tell you which version you have installed.

**Comment by Riiume** [comment]
Okay, I installed Qt 5.9.1 and updated `/usr/lib/x86_64-linux-gnu/qtchooser/default.conf` to point to it, so now I have:

```
needle@Davinlu-Linvega:~/monero-core$ qmake -v
QMake version 3.1
Using Qt version 5.9.1 in /opt/Qt/5.9.1/gcc_64/lib
```

This seems to have fixed the Q_ENUM error.

However, now it's encountering a new error and I'm not sure what exactly to make of it:

```
/home/needle/monero-core/monero/lib/libwallet_merged.a(wallet2.cpp.o): In function `tools::wallet2::load(std::string const&, std::string const&)':
wallet2.cpp:(.text+0x193c1): undefined reference to `boost::filesystem::detail::copy_file(boost::filesystem::path const&, boost::filesystem::path const&, boost::filesystem::detail::copy_option, boost::system::error_code*)'
wallet2.cpp:(.text+0x19923): undefined reference to `boost::filesystem::detail::copy_file(boost::filesystem::path const&, boost::filesystem::path const&, boost::filesystem::detail::copy_option, boost::system::error_code*)'
collect2: error: ld returned 1 exit status
make: *** [release/bin/monero-wallet-gui] Error 1
```

, specifically `undefined reference to `boost::filesystem::detail::copy_file(boost::filesystem::path const&, boost::filesystem::path const&, boost::filesystem::detail::copy_option, boost::system::error_code*)`.

This is odd because it's able to find Boost when it's compiling monero-cli and monerod, it's just during the GUI compilation that it's encountering this Boost-related error.

**Comment by Jaqueeee** [comment]
Have you checked if those boost env vars are correct? i.e do you have the libboost_*.a files in `/usr/local/lib` and the *.hpp files in` /usr/local/include/boost`?

the `BOOST_INCLUDEDIR` seems wrong. Usually it is `/usr/local/include` (without the boost folder at the end) 

For the specific error above you should make sure that boost_filesystem is installed. Make sure you have` /usr/local/include/boost/filesystem.hpp` and `/usr/local/include/libboost_filesystem.a`
