### ISSUE TITLE
Possible error in build instructions in ReadMe.md

### ISSUE THREAD

**Issue by taushet** [monero-project/monero-core#83]
Following the instructions to the letter, this happened:

    minertuxalpha@minertuxalpha-desktop:~/monero-core$ qmake
    Project MESSAGE: Building with libunwind
    WARNING: DESTDIR: Cannot access directory 'release/bin'
    WARNING: langrel: Cannot access directory '/home/minertuxalpha/monero-core/release/bin/translations'
    WARNING: langrel: Cannot access directory '/home/minertuxalpha/monero-core/release/bin/translations'
    WARNING: langrel: Cannot access directory '/home/minertuxalpha/monero-core/release/bin/translations'
    WARNING: langrel: Cannot access directory '/home/minertuxalpha/monero-core/release/bin/translations'
    WARNING: langrel: Cannot access directory '/home/minertuxalpha/monero-core/release/bin/translations'
    Failure to open file: /home/minertuxalpha/monero-core/Makefile
    Unable to generate makefile for: /home/minertuxalpha/monero-core/monero-core.pro

However when  `sudo qmake:`

    minertuxalpha@minertuxalpha-desktop:~/monero-core$ sudo qmake
    Project MESSAGE: Building with libunwind

...it works fine. Just me, or everyone?

**Comment by jwinterm** [comment]
Did you clone the repo as root or something? You should be able to access directories in your home folder.

**Comment by taushet** [comment]
I know it seems strange, but no. I made a new terminal and followed the instructions to the letter. Is there any *downside* to doing it with sudo?

**Comment by taushet** [comment]
Fresh install of Ubuntu 12.04.1 LTS.

**Comment by mbg033** [comment]
There's definitely nothing that requires root privileges.

**Comment by mbg033** [comment]
Also, alternatively you can just invoke build.sh in the fresh (just cloned) project directory

**Comment by dternyak** [comment]
Definitely just you, seems like a permission error. Fix with chmod
