### ISSUE TITLE
Payment ID rejection with 106 character address

### ISSUE THREAD

**Issue by The13thDoc** [monero-project/monero-core#831]
I'm getting a rejection (red background) for the payment ID in both **Send** and **Address book**. It's not accepting 16 or 64 character IDs (or anything in between). I'm not able to send because of this. 

I'm running the downloaded binary for Linux 64. The checksum matches.

It should be mentioned that there is inconsistency in labeling among the fields:
* Send: *16 or 64 hexadecimal characters*
* Address book: *Paste 64 hexadecimal characters*
* Receive: *16 hexadecimal characters*

**Comment by stoffu** [comment]
An address with 106 characters is called "integrated address" which already includes an 8-byte (i.e. 16-character) payment ID. As such, you can't additionally specify yet another payment ID with it.

**Comment by The13thDoc** [comment]
Yep. Just figured that out from my stack exchange post. I completely missed that one.
