### ISSUE TITLE
Monero program does not clean up the upnp record when exiting.

### ISSUE THREAD

**Issue by a8l1vy** [monero-project/monero-core#839]
Need to clean up the 18080 port mapping.

**Comment by a8l1vy** [comment]
Yes. Then improve it. Thank you. Close the issue.

**Comment by MaxXor** [comment]
Here: https://github.com/monero-project/monero/pull/2376

**Comment by a8l1vy** [comment]
Thank you very much for your help.

**Comment by MaxXor** [comment]
A donation? Not for that, thanks though.

**Comment by a8l1vy** [comment]
Okay, you can close this issues.

**Comment by dEBRUYNE-1** [comment]
+resolved
