### ISSUE TITLE
Rename monero-core to monero-gui

### ISSUE THREAD

**Issue by qertoip** [monero-project/monero-core#855]
Can we rename this github repo to "monero-gui"? This is super misleading for newcomers. Let's make an impression of a clean project! :)

We could also change the description to "GUI for Monero cryptocurrency".

Thanks in advance!

**Comment by MaxXor** [comment]
Please add your comment to this already existing issue: #674

**Comment by qertoip** [comment]
Thanks @MaxXor! Commented.

**Comment by dEBRUYNE-1** [comment]
+duplicate
