### ISSUE TITLE
Tiny wallet password modal on load

### ISSUE THREAD

**Issue by taushet** [monero-project/monero-core#86]
Ubuntu 16.04.1 LTS

![screenshot from 2016-10-23 23-09-09](https://cloud.githubusercontent.com/assets/21345262/19629470/695c8044-9976-11e6-9ad9-8939c098fa38.png)

**Comment by dternyak** [comment]
Duplicate of https://github.com/monero-project/monero-core/issues/26
Recommend closing

**Comment by medusadigital** [comment]
fixed by https://github.com/monero-project/monero-core/pull/95, can be closed

**Comment by taushet** [comment]
Fixed by #95 and closed! Thanks for heads up @medusadigital
