### ISSUE TITLE
Add grey separator line above Send and below Settings

### ISSUE THREAD

**Issue by dEBRUYNE-1** [monero-project/monero-core#860]
Reported by scoobybejesus [on reddit](https://www.reddit.com/r/Monero/comments/6wlzm1/help_out_with_testing_the_upcoming_gui_release/):

-The gray separator lines between the Send, Address Book, etc tabs on the left hand side look good. And I think there should be another line above Send and another below Settings.

**Comment by dEBRUYNE-1** [comment]
+UI/UX

**Comment by dEBRUYNE-1** [comment]
+UX

**Comment by MaxXor** [comment]
I got mixed opinions with the new separators, I'm not sure if they look that good.

![separator](https://user-images.githubusercontent.com/7271470/30434902-b507e72a-9968-11e7-80ab-0d8c670be4a5.png)

**Comment by dEBRUYNE-1** [comment]
Perhaps only add the bottom one? The top one makes the GUI less aesthetic in my opinion.
