### ISSUE TITLE
History :: Filter validation

### ISSUE THREAD

**Issue by M5M400** [monero-project/monero-core#88]
values for Date and Amount filters can be set in unlogical way:

"Date from" can be bigger than "Date to" and vice versa
"Amount from" can be bigger than "Amount to" and vice versa

Input boxes for amounts also accept alphanumeric/special characters

![screenshot from 2016-10-25 14-03-04](https://cloud.githubusercontent.com/assets/22886679/19685233/db570926-9abb-11e6-830b-96499f9cbe55.png)

**Comment by dEBRUYNE-1** [comment]
This is a bit odd. I have been testing this with @medusadigital and back then it worked perfectly. 

Could you try to use an integrated address and see what happens?

Also, which commit did you compile on?

**Comment by mbg033** [comment]
Fixed here: https://github.com/monero-project/monero-core/pull/120

**Comment by fluffypony** [comment]
Closing as fixed
