### ISSUE TITLE
Two Linux files in the .zip file for Windows

### ISSUE THREAD

**Issue by rbrunner7** [monero-project/monero-core#886]
The .zip file *monero-gui-win-x64-v0.11.0.0.zip* for Windows contains the following 2 files that are Linux files almost for sure, with no use and no role on Windows: *libcrypto.a* and *libssl.a*

(I noticed this while updating the Windows installer for the new release. I did not add the files to the install script, and the GUI wallet seems to perfectly run without those two files.)

**Comment by MaxXor** [comment]
Yes, they should get removed.

**Comment by dEBRUYNE-1** [comment]
+bug

**Comment by dEBRUYNE-1** [comment]
+resolved
