### ISSUE TITLE
libjasper

### ISSUE THREAD

**Issue by danrmiller** [monero-project/monero-core#900]
See https://build.getmonero.org/builders/monero-core-win64/builds/946/steps/deploy/logs/stdio

```cp: cannot stat '/mingw64/bin/libjasper-1.dll': No such file or directory```

https://github.com/monero-project/monero-core/blob/master/windeploy_helper.sh

I am trying to do a static build, do we need to include libjasper?

If we include libjasper, do we need to include a copyright notice or license file?

**Comment by danrmiller** [comment]
@mbg033

**Comment by dEBRUYNE-1** [comment]
+resolved.

**Comment by dEBRUYNE-1** [comment]
+resolved
