### ISSUE TITLE
[BUG] Number of confirmations not visible on the History page. 

### ISSUE THREAD

**Issue by dEBRUYNE-1** [monero-project/monero-core#905]
Reported by charutocafe on IRC:

>Since the latest GUI release confirmations seemed to have disappeared from the transaction history - we can no longer see "(x/10 Confirmations)" in front of the block weight for unconfirmed transactions.

**Comment by dEBRUYNE-1** [comment]
+bug

**Comment by danrmiller** [comment]
+bug

(An error was returned from github trying to set this label via the api, trying again)
