### ISSUE TITLE
Can't create transaction.

### ISSUE THREAD

**Issue by AwfulCrawler** [monero-project/monero-core#91]
The following error occurred when trying to send a transaction. (OS = Ubuntu 16.04)

> Can't create transaction: internal error: histogram reports no outputs for 2000000000000, not even ours

Steps leading up to it:

1) Running GUI and daemon on one computer and CLI + daemon on another
2) Sent 2XMR from CLI wallet to GUI wallet
3) XMR was received.
4) After balance was unlocked, try to send 1 XMR to another wallet.
5) Error message as shown above.

Screenshot shown below:

![screenshot from 2016-10-30 09-51-27](https://cloud.githubusercontent.com/assets/18298280/19832766/440c0e0a-9e89-11e6-93a2-a14c45efa779.png)

**Comment by Jaqueeee** [comment]
Is this on main or testnet?

**Comment by AwfulCrawler** [comment]
It was on mainnet.  Ran both monerod and monero-core without any command line options.

**Comment by Jaqueeee** [comment]
about the sync: It's "normal" behavior. The daemon block height is cached for some time in the wallet. So this could happen if wallet caches block height from daemon that isn't fully synced.

**Comment by Jaqueeee** [comment]
Ok. It seems there's no other trivial ways of changing that config folder name. So it's up to you @fluffypony if you wan't to close this and continue using "The Monero Project" as folder name.

**Comment by fluffypony** [comment]
@Jaqueeee I'm being dumb, I can't see the config folder in the screenshot...plz help:)

**Comment by Jaqueeee** [comment]
Lol. I'm the dumb one here @fluffypony. Posted this comment on wrong issue. See https://github.com/monero-project/monero-core/pull/96 :)

**Comment by Jaqueeee** [comment]
I have experienced this issue on two scenarios. 
1. When daemon isn't fully synced (fixed by https://github.com/monero-project/monero-core/issues/99)
2. When using 0.10 daemon. Will be fixed when new daemon is released. Until then you need to build own daemon from master branch.
