### ISSUE TITLE
[Feature] Show the version somewhere on the GUI screen (or have an 'About' button) (0.11.1.0)

### ISSUE THREAD

**Issue by ronohara** [monero-project/monero-core#934]
The cli supports --version as a command, and the GUI needs to present this information somewhere as well.

I opened this issue in the wrong repo...  (monero-core) #2733.  I was advised that version is displayed on the settings screen. It is not.

Screen shot of Settings page https://postimg.org/image/1esaw4ia8b/   ...I have checked all the other screens too. None of them display the version.

**Comment by dEBRUYNE-1** [comment]
If you scroll down or drag the page you'll see the version number. It's under `Debug info`.

**Comment by ronohara** [comment]
Ok -- I finally worked out how 'scroll' works in the GUI - but it is not obvious because there are no scroll bars indicating that the screen content extends beyond the visible pane, and as a result you have to guess, and work out that you use the mouse to drag the contents up/down.

Scroll bars are the conventional way to offer scrolling, and indicate there is more content.
