### ISSUE TITLE
[Feature] Optionally auto connect to remote daemon

### ISSUE THREAD

**Issue by ronohara** [monero-project/monero-core#937]
Currently, if you configure the GUI to use a remote daemon, you need to manually connect to that daemon each time to start the wallet.

Please add a tick box to (optionally) auto connect to the remote daemon on startup.

**Comment by Jaqueeee** [comment]
AFAIK this is not the current behavior. The remote node is supposed to get saved and be reused automatically after a restart. Are you saying it doesn't work like that for you? In that case, please provide some more information about OS and GUI version.

**Comment by ronohara** [comment]
You are right.... the GUI  does auto connect.
