### ISSUE TITLE
GUI sets refresh-from-block-height to a distant future block

### ISSUE THREAD

**Issue by stevesbrain** [monero-project/monero-core#955]
_I had posted this at https://github.com/monero-project/monero/issues/2802 but I realised it may be a GUI-project-specific issue, so I've cross-posted it here_

Hi all,

Just been playing around with testnet, and noticed that the GUI (and Monerujo) both set the wallets `refresh-from-block-height` to a block far in the future (in my testing, approximately 27850 blocks further down the line). I am making the assumption this is not by design, as it has the effect that a transaction sent to the wallet will show as pending, but once assigned a block + confirmed it will disappear. 

Manually setting the refresh-from-block-height to a lower value and then rescanning the blockchain allows the balance to appear.

**Comment by Jaqueeee** [comment]
Please provide some more information. Which version of GUI? Official bins or custom built? On mainnet or testnet?

**Comment by stevesbrain** [comment]
@Jaqueeee Official binaries (the release version ones), version 0.11.1. No custom build, and testnet as mentioned in OP :)

**Comment by Jaqueeee** [comment]
Thanks. Known issue on testnet. Fixed in https://github.com/monero-project/monero/pull/2342, merged in master. 
+resolved

**Comment by Jaqueeee** [comment]
Same as https://github.com/monero-project/monero/issues/2775

**Comment by stevesbrain** [comment]
My apologies for not seeing that beforehand - thanks for pointing me in the right direction, and being willing to assist :)
