### ISSUE TITLE
Transaction history should be sorted descending by height per default

### ISSUE THREAD

**Issue by medusadigital** [monero-project/monero-core#98]
Transaction history should be sorted descending by height per default

**Comment by M5M400** [comment]
or alternatively fix the 'sort by date' function. currently it only sorts correctly by day, leaving transactions of the same day unsorted

![screenshot from 2016-10-27 15-17-51](https://cloud.githubusercontent.com/assets/22886679/19921885/4f99dcd0-a0e0-11e6-99e3-fe2e3f02c5b1.png)

**Comment by taushet** [comment]
Can the date/time be converted to timestamp and sorted thereafter? This seems like a simple one.

**Comment by mbg033** [comment]
https://github.com/monero-project/monero-core/pull/104

**Comment by M5M400** [comment]
@mbg033 date sort fix confirmed, thx

**Comment by medusadigital** [comment]
initial sorting not implemented yet (which weas the reason for this ticket in the first place), issue has to stay open

**Comment by mbg033** [comment]
https://github.com/monero-project/monero-core/pull/119
